.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright (C) 1996 Andries Brouwer (aeb@cwi.nl)
.\" Copyright (C) 1996 Markus Kuhn.
.\"
.\" [This version merged from two independently written pages - aeb]
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" 1996-04-12  Andries Brouwer <aeb@cwi.nl>
.\" 1996-04-13  Markus Kuhn <mskuhn@cip.informatik.uni-erlangen.de>
.\" Traduction Christophe Blaess
.\" Màj 18/07/2003 LDP-1.56
.\" Màj 27/06/2005 LDP-1.60
.\"
.TH FDATASYNC 2 "18 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
fdatasync \- synchronise des données en mémoire avec un fichier sur disque.
.SH SYNOPSIS
.B #include <unistd.h>
.sp
.BI "int fdatasync(int " fd );
.SH DESCRIPTION
.B fdatasync
vide tous les buffers de données du fichier vers le disque (avant que l'appel
ne revienne). Il ressemble à
.B fsync
mais ne met pas nécessairement à jour les méta-données comme l'heure d'accès.

Les applications accédant à des bases de données ou des fichiers journaux
écrivent souvent de petits fragments de données (une ligne de texte par exemple)
et appellent
.B fsync
immédiatement pour être sûr du stockage sur disque. Malheureusement,
.B fsync
va déclencher deux écritures\ : une pour les données et une pour
mettre à jour la date de modification enregistrée dans l'i-noeud.
Si la date de modification n'est pas importante pour l'application,
alors
.B fdatasync
peut être invoquée pour éviter l'accès inutile à l'i-noeud.
.SH "VALEUR RENVOYÉE"
L'appel renvoie zéro s'il réussit et \-1 s'il échoue auquel cas
.I errno
contient le code d'erreur.
.SH ERREURS
.TP
.B EBADF
.I fd
n'est pas un descripteur de fichier ouvert en écriture.
.TP
.BR EROFS ", " EINVAL
.I fd
correspond à un fichier spécial ne supportant pas la synchronisation.
.TP
.B EIO
Une erreur d'entrée/sortie s'est produite.
.SH BOGUES
Actuellement (Linux 2.2)
.B fdatasync
est équivalent à
.BR fsync .
.SH DISPONIBILITÉ
Sur les systèmes POSIX sur lesquels
.B fdatasync
est disponible, la constante symbolique
.B _POSIX_SYNCHRONIZED_IO
est définie dans <unistd.h> comme étant une valeur supérieure à 0. (Voir aussi
.BR sysconf (3).)
.\" POSIX 1003.1-2001: devrait être définie à -1, 0 ou 200112L.
.\" -1: indisponible, 0: demander en utilisant sysconf().
.\" glibc les définit à 1.
.SH "CONFORMITÉ"
POSIX1b (anciennement POSIX.4)
.SH "VOIR AUSSI"
.BR fsync (2)

B.O. Gallmeister, POSIX.4, O'Reilly, pp. 220-223 and 343.
.SH TRADUCTION
Christophe Blaess, 1996-2003.
