.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Modified 21 Aug 1994 by Michael Chastain (mec@shell.portal.com):
.\"   Removed note about old libc (pre-4.5.26) translating to 'sync'.
.\" Modified 15 Apr 1995 by Michael Chastain (mec@shell.portal.com):
.\"   Added 'see also' section.
.\"
.\" 
.\" Traduction  10/10/1996 Christophe BLAESS (ccb@club-internet.fr)
.\" màj 30/05/2001 LDP-man-pages-1.36
.\" màj 18/07/2003 LDP-man-pages-1.56
.\" màj 30/07/2003 LDP-man-pages-1.58
.TH FSYNC 2 "30 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
fsync \- Synchroniser un fichier en mémoire avec le disque.
.SH SYNOPSIS
.B #include <unistd.h>
.sp
.BI "int fsync (int " fd );
.sp
.BI "int fdatasync (int " fd);
.SH DESCRIPTION
.B fsync
copie sur le disque tous les morceaux encore en mémoire d'un fichier, et attend
que le périphérique signale que toutes les portions sont stockées.
Cet appel-système met également à jour les informations d'état du fichier.
Il ne s'assure pas obligatoirement que les informations concernant le
répertoire aient atteint le disque. Pour cela, un appel explicite de
.B fsync
sur le descripteur de fichier du répertoire est nécessaire.


.SH "VALEUR RENVOYÉE"
Les appels-système renvoient 0 s'ils reussissent, ou \-1 s'ils échouent, auquel cas
.I errno
contient le code d'erreur.
.SH ERREURS
.TP
.B EBADF
.B fd
n'est pas un descripteur de fichier valide ouvert en écriture.
.TP
.B EROFS ", " EINVAL
.B fd
est associé à un type de fichier spécial qui ne permet pas de synchronisation.
.TP
.B EIO
Une erreur s'est produite pendant la synchronisation.
.SH NOTES
.B fdatasync
effectue la même chose que
.B fsync
mais il n'envoie sur le disque que les données de l'utilisateur, pas les 
informations d'état du fichier, ni les horodatages.
.PP
Si le disque dur dispose d'un tampon en écriture, les données ne
sont peut être pas enregistrées définitivement lorsque
.BR fsync
se termine.
.LP
Lorsqu'un système de fichiers ext2 est monté avec l'option
.IR sync ,
les entrées de répertoires sont également synchronisées lors de l'appel à
.BR fsync .
.LP
Sur les noyaux antérieurs au 2.4, 
.B fsync
peut être sensiblement inefficace sur les gros fichiers.
Une autre solution peut être l'utilisation de l'attribut
.I O_SYNC
lors de l'invocation de
.BR open (2).
.SH COMPATIBILITÉ
POSIX.1b (précédement POSIX.4)
.SH "VOIR AUSSI"
.BR bdflush (2),
.BR fdatasync (2),
.BR open (2),
.BR sync (2),
.BR mount (8),
.BR update (8),
.BR sync (8).
.SH TRADUCTION
Christophe Blaess, 1996-2003.
