.\" Copyright 1995 Andries Brouwer (aeb@cwi.nl)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Written 10 June 1995 by Andries Brouwer (aeb@cwi.nl)
.\"
.\" 
.\" Traduction  10/10/1996 Christophe BLAESS (ccb@club-internet.fr)
.\" Mise a jour 8/04/97
.\" Mise a Jour 21/09/98 LDP-man-pages-1.20
.\" Mise a Jour 30/05/01 LDP-man-pages-1.36
.\" Mise a Jour 18/07/03 LDP-man-pages-1.56
.TH LLSEEK 2 "18 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
_llseek \- Positionner la tête de lecture/écriture dans un fichier.
.SH SYNOPSIS
.B #include <unistd.h>
.sp
.B #include <linux/unistd.h>
.sp
.B _syscall5(int, _llseek, uint, fd, ulong, hi, ulong, lo, loff_t *, res, uint, wh);
.sp
.BI "int _llseek(unsigned int " fd ", unsigned long " offset_high ", unsigned long " offset_low ", loff_t * " result ", unsigned int " whence );
.SH DESCRIPTION
La fonction
.B _llseek
place la tête de lecture/écriture du fichier associé à
.I fd
à la position
.I (offset_high << 32) | offset_low
(en octets) par rapport au début du fichier, à la position courante, ou à la
fin du fichier, suivant que la valeur
.I  whence
soit
.BR SEEK_SET ,
.BR SEEK_CUR ,
ou
.BR SEEK_END ,
respectivement.
La fonction retourne la nouvelle position dans l'argument
.IR result .

.SH "VALEUR RENVOYÉE"
En cas de réussite,
.B _llseek
renvoie 0, sinon il renvoie \-1, auquel cas
.I errno
contient le code d'erreur.
.SH ERREURS
.TP
.B EBADF
.I fd
n'est pas un descripteur de fichier ouvert.
.TP
.B EINVAL
.I whence
est invalide.
.SH "CONFORMITÉ"
Cette fonction est spécifique à Linux et ne doit pas être employée dans
des programmes conçus pour être portables.
.SH "VOIR AUSSI"
.BR lseek (2)
.SH TRADUCTION
Christophe Blaess, 1996-2003.
