.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" 1995-11-26  Markus Kuhn <mskuhn@cip.informatik.uni-erlangen.de>
.\"      First version written
.\"
.\" Traduction  12/10/1996 Christophe BLAESS (ccb@club-internet.fr)
.\" Mise a Jour 8/04/97
.\" Mise a Jour 18/07/2003 LDP-1.56
.TH MUNLOCKALL 2 "18 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
munlockall \- Réautoriser la pagination pour le processus en cours.
.SH SYNOPSIS
.nf
.B #include <sys/mman.h>
.sp
\fBint munlockall(void);
.fi
.SH DESCRIPTION
.B munlockall
revalide la pagination pour toutes les pages de l'espace
d'adressage du processus en cours.

Il n'y a pas d'empilement des verrouillages mémoire, ce qui
signifie qu'une page verrouillée plusieurs fois par
.B mlock
ou
.B mlockall
sera libérée en un seul appel à
.B munlock
pour la zone mémoire correspondante ou par un appel à
.BR munlockall.
Les pages qui sont verrouillées par plusieurs zones, ou
par plusieurs processus restent en mémoire vive tant qu'il
y a au moins un processus ou une zone qui les verrouillent.

Sur les systèmes POSIX où
.B mlockall
et
.B munlockall
sont disponibles, la constante symbolique
.B _POSIX_MEMLOCK
est définie dans <unistd.h>
.SH "VALEUR RENVOYÉE"
.B munlockall
renvoie 0 si il réussit, ou \-1 s'il échoue, auquel cas
.I errno
contient le code d'erreur.
.SH CONFORMITÉ
POSIX.1b, SVr4
.SH "VOIR AUSSI"
.BR mlockall (2),
.BR mlock (2),
.BR munlock (2)
.SH TRADUCTION
Christophe Blaess, 1996-2003.
