.\" Copyright (C) 1999 Joseph Samuel Myers.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Traduction  12/11/1999 Christophe BLAESS (ccb@club-internet.fr)
.\" LDP man-pages 1.24
.\" MàJ 18/07/2003 LDP man-pages 1.56
.TH PREAD 2 "18 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
pread, pwrite \- Lire ou écrire à une position donnée d'un descripteur de fichier.
.SH SYNOPSIS
.B #define _XOPEN_SOURCE 500
.sp
.B #include <unistd.h>
.sp
.BI "ssize_t pread(int " fd ", void *" buf ", size_t " nombre ", off_t " position );
.sp
.BI "ssize_t pwrite(int " fd ", const void *" buf ", size_t " nombre ", off_t " position );
.fi
.SH DESCRIPTION
.B pread()
lit au maximum le
.I nombre
indiqué d'octets depuis le descripteur
.IR fd ,
à la
.I position
mesurée depuis le début du fichier, et les place dans la zone commençant à l'adresse
.IR buf .
La position de la tête de lecture du fichier n'est pas modifiée par cet appel-système.
.PP
.B pwrite()
lit au maximum le
.I nombre
indiqué d'octets dans la zone mémoire pointée par
.IR buf ,
et les écrit à la
.I position
(mesurée depuis le début du fichier)
dans le descripteur
.IR fd .
La position de la tête d'écriture du fichier n'est pas modifiée.
.PP
Dans les deux cas, le fichier décrit par
.I fd
doit permettre le positionnement.
.SH VALEUR RENVOYÉE
S'ils réussissent, ces appels systèmes renvoient le nombre d'octets lus
ou écrits (0 indiquant que rien n'a été écrit dans le cas de \fBpwrite\fR, ou
la fin du fichier dans le cas de \fBpread\fR).
En cas d'échec, ils renvoient \-1, et remplissent la variable globale
.I errno
en conséquence.
.SH ERREURS
.B pread
peut échouer et fournir dans
.I errno
n'importe quelle erreur indiquée par \fBread\fR(2) ou \fBlseek\fR(2).
.B pwrite
peut échouer et fournir dans
.I errno
n'importe quelle erreur indiquée par \fBwrite\fR(2) ou \fBlseek\fR(2).
.SH "CONFORMITÉ"
Unix98
.SH HISTORIQUE
Les appels systèmes \fBpread\fR et \fBpwrite\fR ont été ajoutés dans le
noyau Linux 2.1.60. Les points d'entrée dans la table des appels i386
furent instaurés dans la version 2.1.69. Le support par la bibliothèque C,
y compris l'émulation sur les anciens noyaux sans ces appels systèmes, fut
ajouté dans la GlibC 2.1.
.SH "VOIR AUSSI"
.BR read (2),
.BR write (2),
.BR lseek (2)
.SH TRADUCTION
Christophe Blaess, 1996-2003.
