.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" This manpage is Copyright (C) 1992 Drew Eckhardt;
.\"                               1993 Michael Haardt, Ian Jackson.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Modified Sat Jul 24 00:39:47 1993 by Rik Faith (faith@cs.unc.edu)
.\"
.\" Traduction 13/10/1996 par Christophe Blaess (ccb@club-internet.fr)
.\" Mise a Jour 8/04/97
.\" màj 10/12/1997 (LDP man-pages 1.18)
.\" màj 18/07/2003 (LDP man-pages 1.56)
.TH RMDIR 2 "18 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
rmdir \- Supprimer un répertoire.
.SH SYNOPSIS
.B #include <unistd.h>
.sp
.BI "int rmdir(const char *" pathname );
.SH DESCRIPTION
.B rmdir
supprime le répertoire
.I pathname,
lequel doit être vide.

.SH "VALEUR RENVOYÉE"
.BR rmdir
renvoie 0 s'il réussit, ou \-1 s'il échoue, auquel cas
.I errno
est renseigné comme il faut.
.SH ERREURS
.TP 
.B EPERM
Le système de fichier contenant
.IR pathname
ne permet pas la suppression de répertoires.
.TP
.B EFAULT
.IR pathname " pointe en dehors de l'espace d'adressage accessible."
.TP
.B EACCES
Les droits d'écriture dans le répertoire contenant
.IR pathname
ne sont pas autorisés pour l'U-ID effectif du processus,
ou bien un des répertoires de
.IR pathname
ne permet pas le parcours
.TP
.B EPERM
Le répertoire contenant
.I pathname
a son Sticky-bit positionné, 
.RB ( S_ISVTX )
et l'U-ID effectif du processus
n'est pas le même que celui du répertoire à supprimer, ou celui du répertoire
le contenant.
.TP
.B ENAMETOOLONG
.IR pathname " est trop long."
.TP
.B ENOENT
Un répertoire contenu dans 
.I pathname
n'existe pas, ou est un lien symbolique pointant nulle part.
.TP
.B ENOTDIR
.IR pathname ,
ou un élément contenu dans
.IR pathname ,
n'est pas un répertoire.
.TP
.B ENOTEMPTY
.I pathname
contient d'autres éléments que
.BR . " and " .. " ."
.TP
.B EBUSY
.I pathname
est le répertoire de travail, ou le répertoire racine,
d'un autre processus.
.TP
.B ENOMEM
Pas assez de mémoire pour le noyau.
.TP
.B EROFS
.I pathname
correspond à un répertoire sur un système de fichiers en lecture seule.
.TP
.B ELOOP
.I pathname
contient une référence circulaire (à travers un lien symbolique).
.SH "CONFORMITÉ"
SVr4, SVID, POSIX, BSD 4.3
.SH BOGUES
Des problèmes avec le protocole sous-jacent des systèmes de fichiers
NFS peuvent provoquer la disparition inattendue de répertoires
encore utilisés.
.SH "VOIR AUSSI"
.BR rename (2),
.BR mkdir (2),
.BR chdir (2),
.BR unlink (2),
.BR rmdir (1), 
.BR rm (1)
.SH TRADUCTION
Christophe Blaess, 1996-2003.
