.\" Copyright (C), 1994, Graeme W. Wilford. (Wilf.)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Fri Jul 29th 12:56:44 BST 1994  Wilf. (G.Wilford@ee.surrey.ac.uk) 
.\"
.\" Traduction 15/10/1996 par Christophe Blaess (ccb@club-internet.fr)
.\" Mise a Jour 15/04/97
.\" Mise a Jour 19/07/97
.\" Mise a Jour 18/07/2003  LDP-1.56
.TH SETUID 2 "18 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
setuid \- Fixer l'ID de l'utilisateur.
.SH SYNOPSIS
.B #include <sys/types.h>
.br
.B #include <unistd.h>
.sp
.BI "int setuid(uid_t " uid );
.SH DESCRIPTION
.B setuid
fixe l'UID effectif du processus en cours. Si cet UID effectif
est celui du Super\-User, les UID réels et sauvés sont également fixés.
.PP
Sous Linux
.B setuid
est implémenté comme le spécifie Posix, avec l'option _POSIX_SAVED_IDS.
Ceci permet à un programme Set\-UID (autre que root) d'abandonner
tous ses privilèges, d'effectuer des tâches
non-privilégiée, et de retrouver son UID effectif de manière sécurisée.
.PP
Si l'utilisateur est le Super\-User, ou si le programme est Set\-UID
root, des précautions particulières doivent être prises.
La fonction
.B setuid
vérifie l'UID effectif de l'appelant et si c'est le Super\-User,
tous les UID du processus sont mis à
.IR uid.
une fois ceci effectué, il est impossible au programme de retrouver
ses privilèges de Super\-User.
.PP
Ainsi un programme Set\-UID root désireux d'abandonner temporairement
ses privilèges, en prenant l'identité d'un utilisateur non-root, puis
de récupérer ses privilèges par la suite ne doit pas utiliser
.BR setuid .
On peut accomplir ceci en utilisant l'appel (non-POSIX, BSD)
.BR seteuid.
.SH "VALEUR RENVOYÉE"
.B setuid
renvoie 0 s'il réussit, ou \-1 s'il échoue, auquel cas
.I errno
contient le code d'erreur.
.SH ERREURS
.TP
.B EPERM
L'utilisateur n'est pas Super\-User et 
.I uid
ne correspond ni à l'UID réel, ni à l'UID sauvé du processus.
.SH "CONFORMITÉ"
SVr4, SVID, POSIX.1. Pas tout à fait compatible avec l'appel système BSD
4.4, qui positionne l'ensemble des IDs réel, sauvé et effectif. SVr4 indique
une condition d'erreur supplémentaire EINVAL.
.SH "SPÉCIFICITÉS LINUX"
Linux dispose d'un concept d'UID de système de fichiers, qui est normalement
égal à l'UID effectif. L'appel
.B setuid
peut également fixer l'UID de système de fichiers du processus en cours.
Voir
.BR setfsuid (2).
.PP
Si
.RI "l'" uid
est différent de l'ancien UID effectif, le processus ne pourra pas laisser
d'image mémoire (core dump) sur le disque.
.SH "VOIR AUSSI"
.BR getuid (2),
.BR setreuid (2),
.BR seteuid (2),
.BR setfsuid (2).
.SH TRADUCTION
Christophe Blaess, 1996-2003.
