.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright (c) 1992 Drew Eckhardt (drew@cs.colorado.edu), March 28, 1992
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Modified by Michael Haardt (u31b3hs@pool.informatik.rwth-aachen.de)
.\" Modified Sat Jul 24 11:47:53 1993 by Rik Faith (faith@cs.unc.edu)
.\" Modified 22 July 1995 by Michael Chastain (mec@duracef.shout.net):
.\"   Added 'swapflags' argument.
.\" Added historical remark, aeb, 950723.
.\"
.\" Traduction 15/10/1996 par Christophe Blaess (ccb@club-internet.fr)
.\" Mise a Jour 15/04/97
.\" maj 09/04/99 - LDP-man-pages 1.22
.\" maj 18/07/03 - LDP-man-pages 1.56
.TH SWAPON 2 "18 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
swapon, swapoff \- Activer / désactiver un fichier ou un péripherique de swap.
.SH SYNOPSIS
.B #include <unistd.h>
.br
.B #include <asm/page.h>     /* pour avoir PAGE_SIZE */
.br
.B #include <sys/swap.h>
.sp
.BI "int swapon(const char *" path ", int " swapflags );
.br
.BI "int swapoff(const char *" path );
.SH DESCRIPTION
.B swapon
active le swap sur le fichier ou le périphérique en mode bloc indiqué dans
.IR path .
.B swapoff
arrête le swap sur le fichier ou le périphérique en mode bloc indiqué dans
.IR path .
.PP
.B swapon
utilise un argument
.IR swapflags .
Si cet argument
a son bit
.I SWAP_FLAG_PREFER
à 1, la nouvelle zone de swap disposera d'une priorité plus
élevée que la zone de swap par défaut.
La priorité est codée ainsi :
.br
.sp
.I "    (prio << SWAP_FLAG_PRIO_SHIFT) & SWAP_FLAG_PRIO_MASK"
.br
.PP
Cette fonction ne peut être appelée que par le Super\-User.
.SH "PRIORITÉ"
Chaque zone de swap a une priorité, haute ou basse. La priorité
par defaut est basse.
Parmi les zones de basses priorités, les nouvelles zones
sont toujours affectées d'une priorité inférieure à celle
des zones précédentes.
.PP
Toutes les priorités fixées avec l'argument
.I swapflags
sont plus élevées que la priorité par défaut.
Elles peuvent prendre n'importe quelle valeur positive ou 
nulle choisie par l'appelant.
Plus la valeur est haute, plus la priorité est élevée.
.PP
Les pages de swap sont allouées dans les zones par ordre décroissant
de priorité. Pour des zones de priorité différentes, la plus haute
sera toujours remplie entièrement avant d'utiliser la zone
de priorité plus faible.
Si deux ou plus de zones ont la même priorite, et qu'il s'agit de
la plus haute priorité disponible, les pages sont allouées en
utilisant un algorithme Round\-Robin entre elles.
.PP
Sur linux 1.3.6, le noyau suit généralement ces règles, mais il
y a parfois des exceptions.
.SH "VALEUR RENVOYÉE"
En cas de réussite 0 est renvoyé, sinon \-1 est renvoyé et
.I errno
contient le code d'erreur.
.SH ERREURS
De nombreuses erreurs peuvent survenir si
.I path
n'est pas valide.

.TP
.B EPERM
L'utilisateur n'est pas Super\-User ou il y a plus de
.B MAX_SWAPFILES
zones de swap actives (8 sous Linux 1.3.6).
.TP
.B EINVAL
.I path 
existe mais n'est ni un chemin régulier, ni un périphérique bloc.
.TP
.B ENOENT
.I path 
n'existe pas.
.TP
.B ENOMEM 
Pas assez de mémoire pour démarrer le swapping.
.SH "CONFORMITÉ"
Ces fonctions sont spécifiques à Linux et ne doivent pas être employées
dans des programmes destinés à être portables.
.SH NOTES
La partition ou le fichier doivent être préparés par 
.BR mkswap (8).
.SH "VOIR AUSSI"
.BR mkswap (8),
.BR swapon (8),
.BR swapoff (8)
.SH TRADUCTION
Christophe Blaess, 1996-2003.
