.\" Copyright (c) 1994 Peter Tobias <tobias@server.et-inf.fho-emden.de>
.\" This file may be distributed under the GNU General Public License.
.\" Màj 25/07/2003 LDP-1.56
.\" Màj 01/05/2006 LDP-1.67.1
.\"
.TH ISSUE.NET 5 "22 mai 1994" LDP "Manuel de l'administrateur Linux"
.SH NOM
issue.net \- Fichier d'authentification pour les sessions telnet.
.SH DESCRIPTION
Le fichier \fI/etc/issue.net\fP est un fichier texte qui contient un message
ou une identification du système à afficher avant l'invite de connexion d'une
session telnet.
Il peut contenir différentes séquences de caractères «\ \fB%car\fP\ ».
Les séquences suivantes sont supportées par
.BR telnetd "\ :"
.TP
.B %t
\- affiche le terminal utilisé
.TP
.B %h
\- affiche le nom de la machine (FQDN)
.TP
.B %D
\- affiche le nom du domaine NIS
.TP
.B %d
\- affiche l'heure et la date
.TP
.B %s
\- affiche le nom du système d'exploitation
.TP
.B %m
\- montre le type de machine (CPU)
.TP
.B %r
\- affiche la sous-version du système d'exploitation
.TP
.B %v
\- affiche la version du système d'exploitation
.TP
.B %%
\- affiche un caractère «\ %\ » unique.
.PP
.SH FICHIERS
.I /etc/issue.net
.SH "VOIR AUSSI"
.BR telnetd (8)
.SH TRADUCTION
.PP
Ce document est une traduction réalisée par Thierry Vignaud
<tvignaud AT mandriva DOT com> en 1999
et révisée le 2\ mai\ 2006.
.PP
L'équipe de traduction a fait le maximum pour réaliser une adaptation
française de qualité. La version anglaise la plus à jour de ce document est
toujours consultable via la commande\ : «\ \fBLANG=en\ man\ 5\ issue.net\fR\ ».
N'hésitez pas à signaler à l'auteur ou au traducteur, selon le cas, toute
erreur dans cette page de manuel.
