PACKAGE=nfs-utils

include ../Makefile.common

post-build:
	$(call create_link,gssd.8,rpc.gssd.8);
	$(call create_link,idmapd.8,rpc.idmapd.8);
	$(call create_link,lockd.8,rpc.lockd.8);
	$(call create_link,mountd.8,rpc.mountd.8);
	$(call create_link,nfsd.8,rpc.nfsd.8);
	$(call create_link,statd.8,rpc.statd.8);
	$(call create_link,svcgssd.8,rpc.svcgssd.8);
