'\" t
.\" Copyright 2002      Dimitri Papadopoulos (dpo@club-internet.fr)
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\" Traduction : Alain Portal
.\" 30/11/2004 LDP-1.58
.\" Màj 27/06/2005 LDP-1.60
.\" Màj 01/05/2006 LDP-1.67.1
.\"
.TH ISO_8859-9 7 "24 septembre 2002" "Linux" "Manuel du programmeur Linux"
.nh
.SH NOM
iso_8859-9 \- la table de caractères ISO 8859-9 encodée en octal, décimal et
hexadécimal
.SH DESCRIPTION
La norme ISO 8859 inclut plusieurs extensions 8 bits au jeu de caractères
ASCII (également appelé ISO 646-IRV). L'ISO 8859-9 encode les caractères
utilisés dans le turc.
.SS "Alphabets ISO 8859"
L'ensemble des alphabets ISO 8859 se compose de\ :
.P
.TS
l l.
ISO 8859-1	Langues d'Europe de l'Ouest (Latin-1)
ISO 8859-2	Langues d'Europe Centrale et d'Europe de l'Est (Latin-2)
ISO 8859-3	Langues d'Europe du Sud-Est et autres (Latin-3)
ISO 8859-4	Langues scandinave et balte (Latin-4)
ISO 8859-5	Latin/Cyrillique
ISO 8859-6	Latin/Arabe
ISO 8859-7	Latin/Grec
ISO 8859-8	Latin/Hébreu
ISO 8859-9	Latin-1 modifié pour le turc (Latin-5)
ISO 8859-10	Langues lappone/nordique/eskimaude (Latin-6)
ISO 8859-11	Latin/Thaï
ISO 8859-13	Langues de la ceinture baltique (Latin-7)
ISO 8859-14	Celte (Latin-8)
ISO 8859-15	Langues d'Europe de l'Ouest (Latin-9)
ISO 8859-16	Roumain (Latin-10)
.TE
.SS "Caractères ISO 8859-9"
Le tableau suivant affiche les caractères de l'ISO 8859-9 (Latin-5) qui sont
imprimables et non disponibles dans la page de manuel
.BR ascii (7).
La quatrième colonne affichera correctement les glyphes seulement dans un
environnement configuré pour l'ISO 8859-9.

.TS
l l l c lp-1.
Oct	Déc	Hex	Carac	Description
_
240	160	A0	 	Espace insécable
241	161	A1	¡	Point d'exclamation inversé
242	162	A2	¢	Symbole monétaire cent
243	163	A3	£	Symbole monétaire livre
244	164	A4	¤	Symbole monétaire
245	165	A5	¥	Symbole monétaire yen
246	166	A6	¦	Barre verticale interrompue
247	167	A7	§	Symbole section
250	168	A8	¨	Tréma
251	169	A9	©	Symbole copyright
252	170	AA	ª	Indicateur ordinal féminin
253	171	AB	«	Guillemet français ouvrant
254	172	AC	¬	Symbole négation
255	173	AD	­	Trait d'union
256	174	AE	®	Symbole marque déposée
257	175	AF	¯	Macron
260	176	B0	°	Symbole degré
261	177	B1	±	Symbole plus-moins
262	178	B2	²	Exposant 2
263	179	B3	³	Exposant 3
264	180	B4	´	Accent aigu
265	181	B5	µ	Symbole micro
266	182	B6	¶	Symbole paragraphe
267	183	B7	·	Point à mi-hauteur
270	184	B8	¸	Cédille
271	185	B9	¹	Exposant 1
272	186	BA	º	Indicateur ordinal masculin
273	187	BB	»	Guillemet français fermant
274	188	BC	¼	Fraction un quart
275	189	BD	½	Fraction un demi
276	190	BE	¾	Fraction trois quarts
277	191	BF	¿	Point d'interrogation inversé
300	192	C0	À	Lettre majuscule latine A accent grave
301	193	C1	Á	Lettre majuscule latine A accent aigu
302	194	C2	Â	Lettre majuscule latine A accent circonflexe
303	195	C3	Ã	Lettre majuscule latine A tilde
304	196	C4	Ä	Lettre majuscule latine A tréma
305	197	C5	Å	Lettre majuscule latine A avec anneau dessus
306	198	C6	Æ	Lettre majuscule latine AE ligaturée
307	199	C7	Ç	Lettre majuscule latine C cédille
310	200	C8	È	Lettre majuscule latine E accent grave
311	201	C9	É	Lettre majuscule latine E accent aigu
312	202	CA	Ê	Lettre majuscule latine E accent circonflexe
313	203	CB	Ë	Lettre majuscule latine E tréma
314	204	CC	Ì	Lettre majuscule latine I accent grave
315	205	CD	Í	Lettre majuscule latine I accent aigu
316	206	CE	Î	Lettre majuscule latine I accent circonflexe
317	207	CF	Ï	Lettre majuscule latine I tréma
320	208	D0	Ğ	Lettre majuscule latine G accent brève
321	209	D1	Ñ	Lettre majuscule latine N tilde
322	210	D2	Ò	Lettre majuscule latine O accent grave
323	211	D3	Ó	Lettre majuscule latine O accent aigu
324	212	D4	Ô	Lettre majuscule latine O accent circonflexe
325	213	D5	Õ	Lettre majuscule latine O tilde
326	214	D6	Ö	Lettre majuscule latine O tréma
327	215	D7	×	Symbole multiplication
330	216	D8	Ø	Lettre majuscule latine O barré
331	217	D9	Ù	Lettre majuscule latine U accent grave
332	218	DA	Ú	Lettre majuscule latine U accent aigu
333	219	DB	Û	Lettre majuscule latine U accent circonflexe
334	220	DC	Ü	Lettre majuscule latine U tréma
335	221	DD	İ	Lettre majuscule latine I avec un point
336	222	DE	Ş	Lettre majuscule latine S cédille
337	223	DF	ß	Lettre minuscule latine S dur
340	224	E0	à	Lettre minuscule latine A accent grave
341	225	E1	á	Lettre minuscule latine A accent aigu
342	226	E2	â	Lettre minuscule latine A accent circonflexe
343	227	E3	ã	Lettre minuscule latine A tilde
344	228	E4	ä	Lettre minuscule latine A tréma
345	229	E5	å	Lettre minuscule latine A avec anneau dessus
346	230	E6	æ	Lettre minuscule latine AE ligaturée
347	231	E7	ç	Lettre minuscule latine C cédille
350	232	E8	è	Lettre minuscule latine E accent grave
351	233	E9	é	Lettre minuscule latine E accent aigu
352	234	EA	ê	Lettre minuscule latine E accent circonflexe
353	235	EB	ë	Lettre minuscule latine E tréma
354	236	EC	ì	Lettre minuscule latine I accent grave
355	237	ED	í	Lettre minuscule latine I accent aigu
356	238	EE	î	Lettre minuscule latine I accent circonflexe
357	239	EF	ï	Lettre minuscule latine I tréma
360	240	F0	ğ	Lettre minuscule latine G accent brève
361	241	F1	ñ	Lettre minuscule latine N tilde
362	242	F2	ò	Lettre minuscule latine O accent grave
363	243	F3	ó	Lettre minuscule latine O accent aigu
364	244	F4	ô	Lettre minuscule latine O accent circonflexe
365	245	F5	õ	Lettre minuscule latine O tilde
366	246	F6	ö	Lettre minuscule latine O tréma
367	247	F7	÷	Symbole division
370	248	F8	ø	Lettre minuscule latine O barré
371	249	F9	ù	Lettre minuscule latine U accent grave
372	250	FA	ú	Lettre minuscule latine U accent aigu
373	251	FB	û	Lettre minuscule latine U accent circonflexe
374	252	FC	ü	Lettre minuscule latine U tréma
375	253	FD	ı	Lettre minuscule latine I sans point
376	254	FE	ş	Lettre minuscule latine S cédille
377	255	FF	ÿ	Lettre minuscule latine Y tréma
.TE
.SH "VOIR AUSSI"
.BR ascii (7)
.SH TRADUCTION
.PP
Ce document est une traduction réalisée par Alain Portal
<aportal AT univ-montp2 DOT fr> le 29 novembre 2004
et révisée le 2\ mai\ 2006.
.PP
L'équipe de traduction a fait le maximum pour réaliser une adaptation
française de qualité. La version anglaise la plus à jour de ce document est
toujours consultable via la commande\ : «\ \fBLANG=en\ man\ 7\ iso_8859-9\fR\ ».
N'hésitez pas à signaler à l'auteur ou au traducteur, selon le cas, toute
erreur dans cette page de manuel.
