.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\"
.\" Modified, Sun Feb 26 14:52:00 1995, faith@cs.unc.edu
.\" Modified Tue Oct 22 23:48:10 1996 by Eric S. Raymond <esr@thyrsus.com>
.\"
.\" Traduction 22/10/1996 par Christophe Blaess (ccb@club-internet.fr)
.\" Màj 21/07/2003 LDP-1.56
.\" Màj 01/05/2006 LDP-1.67.1
.\"
.TH BCOPY 3 "31 décembre 2002" LDP "Manuel du programmeur Linux"
.SH NOM
bcopy \- Copier un bloc d'octets.
.SH SYNOPSIS
.nf
.B #include <string.h>
.sp
.BI "void bcopy (const void *" src ", void *" dest ", size_t " n );
.fi
.SH DESCRIPTION
La fonction
.BR bcopy ()
copie
.I n
octets depuis
.I src
vers
.IR dest .
Le résultat est correct même si les deux zones se chevauches.
.SH "VALEUR RENVOYÉE"
Aucune.
.SH "CONFORMITÉ"
BSD 4.3. Cette fonction est déconseillée, utilisez plutôt
.BR memcpy
dans les nouveaux programmes. Notez que les deux premiers paramètes
sont inversés par rapport à
.BR memcpy .
.SH "VOIR AUSSI"
.BR memccpy (3),
.BR memcpy (3),
.BR memmove (3),
.BR strcpy (3),
.BR strncpy (3)
.SH TRADUCTION
.PP
Ce document est une traduction réalisée par Christophe Blaess
<http://www.blaess.fr/christophe/> le 22\ octobre\ 1996
et révisée le 2\ mai\ 2006.
.PP
L'équipe de traduction a fait le maximum pour réaliser une adaptation
française de qualité. La version anglaise la plus à jour de ce document est
toujours consultable via la commande\ : «\ \fBLANG=en\ man\ 3\ bcopy\fR\ ».
N'hésitez pas à signaler à l'auteur ou au traducteur, selon le cas, toute
erreur dans cette page de manuel.
