.\" Copyright 2002 Walter Harms(walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.\" Traduction Christophe Blaess <ccb@club-internet.fr>
.\" 21/07/2003 - LDP-1.57
.\" Màj 01/05/2006 LDP-1.67.1
.\"
.TH CATAN 3 "28 juillet 2002" LDP "Manuel du programmeur Linux"
.SH NOM
catan, catanf, catanl \- Fonctions arc tangentes complexes.
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BI "double complex catan(double complex " z );
.sp
.BI "float complex catanf(float complex " z );
.sp
.BI "long double complex catanl(long double complex " z );
.sp
.SH DESCRIPTION
La fonction
.BR catan ()
calcule la version complexe de
.BR atan ().
Si y\ =\ catan(z), alors z\ =\ ctan(y).
La partie réelle de y est choisie dans l'intervalle [-pi/2,pi/2].
.LP
On a
catan(z)\ =\ 1/2i\ clog((1+iz)/(1-iz)).
.SH "CONFORMITÉ"
C99
.SH "VOIR AUSSI"
.BR clog (3),
.BR ccos (3)
.SH TRADUCTION
.PP
Ce document est une traduction réalisée par Christophe Blaess
<http://www.blaess.fr/christophe/> le 21\ juillet\ 2003
et révisée le 2\ mai\ 2006.
.PP
L'équipe de traduction a fait le maximum pour réaliser une adaptation
française de qualité. La version anglaise la plus à jour de ce document est
toujours consultable via la commande\ : «\ \fBLANG=en\ man\ 3\ catan\fR\ ».
N'hésitez pas à signaler à l'auteur ou au traducteur, selon le cas, toute
erreur dans cette page de manuel.
