.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single Unix specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\" Màj 21/07/2003 LDP-1.56
.\" Màj 01/05/2006 LDP-1.67.1
.\"
.TH ISWPRINT 3 "25 juillet 1999" LDP "Manuel du programmeur Linux"
.SH NOM
iswprint \- Vérifier si un caractère large est imprimable.
.SH SYNOPSIS
.nf
.B #include <wctype.h>
.sp
.BI "int iswprint (wint_t " wc );
.fi
.SH DESCRIPTION
La fonction \fBiswprint\fP() est l'équivalent pour les caractères larges de la
fonction \fBisprint\fP(). Elle teste si le caractère large \fIwc\fP appartient à
la classe de caractères «\ print\ ».
.PP
La classe de caractères «\ print\ » est disjointe de la classe «\ cntrl\ ».
.PP
La classe «\ print\ » contient la classe «\ graph\ ».
.SH "VALEUR RENVOYÉE"
La fonction \fBiswprint\fP() renvoie une valeur non nulle si le caractère large
\fIwc\fP appartient à la classe «\ print\ ». Sinon, 0 est renvoyé.
.SH "CONFORMITÉ"
ISO/ANSI C, UNIX98
.SH "VOIR AUSSI"
.BR isprint (3),
.BR iswctype (3)
.SH NOTES
Le comportement de \fBiswprint\fP() dépend de la valeur de la variable courante
de localisation LC_CTYPE.
.SH TRADUCTION
.PP
Ce document est une traduction réalisée par Thierry Vignaud
<tvignaud AT mandriva DOT com> en 2000
et révisée le 2\ mai\ 2006.
.PP
L'équipe de traduction a fait le maximum pour réaliser une adaptation
française de qualité. La version anglaise la plus à jour de ce document est
toujours consultable via la commande\ : «\ \fBLANG=en\ man\ 3\ iswprint\fR\ ».
N'hésitez pas à signaler à l'auteur ou au traducteur, selon le cas, toute
erreur dans cette page de manuel.
