.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 19:42:57 1993 by Rik Faith (faith@cs.unc.edu)
.\" Modified Aug 14 1995 by Arnt Gulbrandsen <agulbra@troll.no>
.\" Modified 2002-07-27 by Walter Harms
.\" 	(walter.harms@informatik.uni-oldenburg.de)
.\"
.\" Traduction 22/10/1996 par Christophe Blaess (ccb@club-internet.fr)
.\" Màj 21/07/2003 LDP-1.56
.\" Màj 30/07/2003 LDP-1.58
.\" Màj 01/05/2006 LDP-1.67.1
.\"
.TH POW 3 "27 juillet 2002" LDP "Manuel du programmeur Linux"
.SH NOM
pow, powf, powl \- Fonction puissance.
.SH SYNOPSIS
.nf
.B #define _GNU_SOURCE
.B #include <math.h>
.sp
.BI "double pow (double " x ", double " y );
.sp
.BI "float powf (float " x ", float " y );
.sp
.BI "long double powl (long double " x ", long double " y );
.fi
.SH DESCRIPTION
La fonction \fBpow\fP() renvoie la valeur de \fIx\fP élevé à la puissance \fIy\fP.
.SH "ERREURS"
.TP
.B EDOM
L'argument \fIx\fP est négatif, et \fIy\fP n'est pas entier. Le résultat
serait un nombre complexe.
.SH NOTES
Pour utiliser les fonctions de la bibliothèque mathématique, il ne faut
pas oublier d'ajouter l'argument \fI\-lm\fP sur la ligne de commande de
\fBcc\fP(1) ou \fBld\fP(1), lors de l'édition des liens.
.SH "CONFORMITÉ"
SVID 3, POSIX, BSD 4.3, ISO 9899
Les variantes float et long double sont des demandes C99.
.SH "VOIR AUSSI"
.BR sqrt (3),
.BR cbrt (3)
.SH TRADUCTION
.PP
Ce document est une traduction réalisée par Christophe Blaess
<http://www.blaess.fr/christophe/> le 22\ octobre\ 1996
et révisée le 2\ mai\ 2006.
.PP
L'équipe de traduction a fait le maximum pour réaliser une adaptation
française de qualité. La version anglaise la plus à jour de ce document est
toujours consultable via la commande\ : «\ \fBLANG=en\ man\ 3\ pow\fR\ ».
N'hésitez pas à signaler à l'auteur ou au traducteur, selon le cas, toute
erreur dans cette page de manuel.
