.\" Hey Emacs! This file is -*- nroff -*- source.
.\" This page is in the public domain. - aeb
.\"
.\" Traduction Christophe Blaess, <ccb@club-internet.fr>
.\" Màj 21/07/2003 LDP-1.56
.\" Màj 01/05/2006 LDP-1.67.1
.\"
.TH PTSNAME 3 "30 janvier 2003" LDP "Manuel du programmeur Linux"
.SH NOM
ptsname \- Obtenir le nom d'un pseudo-terminal esclave.
.SH SYNOPSIS
.nf
.B #include <stdlib.h>
.sp
.BI "char *ptsname(int " fd ");"
.fi
.SH DESCRIPTION
La fonction
.BR ptsname ()
renvoie le nom du périphérique pseudo-terminaml esclave (pty) associé
au pseudo-terminal maître indiqué par
.IR fd .
.SH "VALEUR RENVOYÉE"
Lorsqu'elle réussit, la fonction
.BR ptsname ()
renvoie un pointeur sur une chaîne de stockage statique. Le pointeur ne
doit PAS être libéré.
.PP
Si elle échoue,
.BR ptsname ()
renvoie un pointeur NULL.
.SH "CONFORMITÉ"
POSIX 1003.1-2001.
Cette fonction fait partie du support pty d'Unix 98. Voir
.BR pts (4).
.SH "VOIR AUSSI"
.BR grantpt (3),
.BR ttyname (3),
.BR pts (4)
.SH TRADUCTION
.PP
Ce document est une traduction réalisée par Christophe Blaess
<http://www.blaess.fr/christophe/> le 21\ juillet\ 2003
et révisée le 2\ mai\ 2006.
.PP
L'équipe de traduction a fait le maximum pour réaliser une adaptation
française de qualité. La version anglaise la plus à jour de ce document est
toujours consultable via la commande\ : «\ \fBLANG=en\ man\ 3\ ptsname\fR\ ».
N'hésitez pas à signaler à l'auteur ou au traducteur, selon le cas, toute
erreur dans cette page de manuel.
