.\" Copyright 2003 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.\" Traduction : Alain Portal
.\" 08/07/2005 LDP-1.63
.\" Màj 14/12/2005 LDP-1.65
.\" Màj 01/05/2006 LDP-1.67.1
.\"
.TH PUTGRENT 3 "9 septembre 2003" LDP "Manuel du programmeur Linux"
.SH NOM
putgrent \- Écrire un enregistrement base de données group dans un fichier.
.SH SYNOPSIS
.B #define _GNU_SOURCE
.br
.B #include <grp.h>
.sp
.BI "int putgrent(const struct group *" grp ", FILE *" fp );
.sp
.SH DESCRIPTION
La fonction
.BR putgrent ()
est la fonction complémentaire de
.BR fgetgrent ().
La fonction écrit le contenu de la structure group fournie dans le fichier
pointé par
.IR fp .
La liste des membres doit se terminer par le caractère NULL ou bien être
initialisée à NULL.
.sp
La structure group est définie comme suit\ :
.sp
.RS
.nf
struct group {
      char    *gr_name;      /* nom du groupe          */
      char    *gr_passwd;    /* mot de passe du groupe */
      gid_t   gr_gid;        /* ID du groupe           */
      char    **gr_mem;      /* membres du groupe      */
};
.fi
.RE
.SH "VALEUR RENVOYÉE"
La fonction renvoie zéro si elle réussit et une valeur non nulle s'il y a
une erreur.
.SH "VOIR AUSSI"
.BR getgrent (3),
.BR fgetgrent (3),
.BR group (5)
.SH TRADUCTION
.PP
Ce document est une traduction réalisée par Alain Portal
<aportal AT univ-montp2 DOT fr> le 8 juillet 2005
et révisée le 2\ mai\ 2006.
.PP
L'équipe de traduction a fait le maximum pour réaliser une adaptation
française de qualité. La version anglaise la plus à jour de ce document est
toujours consultable via la commande\ : «\ \fBLANG=en\ man\ 3\ putgrent\fR\ ».
N'hésitez pas à signaler à l'auteur ou au traducteur, selon le cas, toute
erreur dans cette page de manuel.
