.\" Copyright (C) 2002 Andries Brouwer <aeb@cwi.nl>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" This replaces an earlier man page written by Walter Harms
.\" <walter.harms@informatik.uni-oldenburg.de>.
.\"
.\" Màj 21/07/2003 LDP-1.56
.\" Màj 08/07/2005 LDP-1.63
.\" Màj 01/05/2006 LDP-1.67.1
.\"
.TH QECVT 3 "25 août 2002" LDP "Manuel du programmeur Linux"
.SH NOM
qecvt, qfcvt, qgcvt \- Conversion de nombres réels en chaînes.
.SH SYNOPSIS
.B #include <stdlib.h>
.sp
.BI "char *qecvt(long double " nombre ", int " nb_chiffres ", int *" decpt ,
.BI "int *" sign );
.sp
.BI "char *qfcvt(long double " nombre ", int " nb_chiffres ", int *" decpt ,
.BI "int *" sign );
.sp
.BI "char *qgcvt(long double " nombre ", int " nb_chiffres ", char *" buf );
.SH DESCRIPTION
Les fonctions
.BR qecvt (),
.BR qfcvt ()
et
.BR qgcvt ()
sont identiques à
.BR ecvt (),
.BR fcvt ()
et
.BR gcvt ()
respectivement, excepté qu'elles prennent un nombre au format
.B "long double"
via l'argument
.IR nombre .
Voir
.BR ecvt (3)
et
.BR gcvt (3).
.SH NOTES
Ces fonctions sont obsolètes. L'utilisation de
.IR sprintf ()
est recommandée à la place de ces fonctions.
.SH "CONFORMITÉ"
SysVr4.0. Ces fonctions sont absentes de la majorité des
implémentations Unix, à l'exception notable de SunOS. Elles ne sont pas
supportées par libc4 et libc5 mais le sont par la glibc (aka libc6).
.SH "VOIR AUSSI"
.BR ecvt (3),
.BR ecvt_r (3),
.BR gcvt (3),
.BR sprintf (3)
.SH TRADUCTION
.PP
Ce document est une traduction réalisée par Thierry Vignaud
<tvignaud AT mandriva DOT com> en 2002
et révisée le 2\ mai\ 2006.
.PP
L'équipe de traduction a fait le maximum pour réaliser une adaptation
française de qualité. La version anglaise la plus à jour de ce document est
toujours consultable via la commande\ : «\ \fBLANG=en\ man\ 3\ qecvt\fR\ ».
N'hésitez pas à signaler à l'auteur ou au traducteur, selon le cas, toute
erreur dans cette page de manuel.
