.\" Written Sat Mar  8 10:35:08 MEZ 1997 by J. "MUFTI" Scheurich (mufti@csv.ica.uni-stuttgart.de)
.\" Traduction 31/05/1998 par Christophe Blaess (ccb@club-internet.fr)
.\" LDP-man-pages 1.19
.\" màj 26/06/2000 LDP 1.30
.\" màj 30/08/2000 LDP 1.31
.\" màj 21/07/2003 LDP 1.56
.TH __SETFPUCW 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
__setfpucw \- Positionner le mot de contrôle du FPU sur les machines i386 (obsolète).
.SH SYNOPSIS
.B #include <i386/fpu_control.h>
.sp
.BI "void __setfpucw((unsigned short) " mot_de_controle );
.br
.SH DESCRIPTION
.B __setfpucw
transfere le
.I mot_de_controle
dans les registres du FPU (Floating Point Unit, unité de calcul en virgule
flottante), sur les machines reposant sur une architecture à base de i386.
Ceci permet de commander la précision des calculs en virgule flottante, les
arrondis, et les exceptions mathématiques.
.SH EXEMPLE

.BR __setfpucw(0x1372)

Positionne le mot de contrôle du FPU sur une machine i386 ainsi :
.br
     - Précision étendue
.br     
     - Arrondi au plus proche
.br     
     - Exceptions si débordement, division par zéro, ou NaN (not a number)
.br 
.SH DISPONIBILITÉ
Depuis la GlibC 2.1, cette fonction n'existe plus. Il y a quelques fonctions
nouvelles de l'ISO C9X, dont les prototypes se trouvent dans
.IR /usr/include/fenv.h ,
permettant de commander le mode d'arrondi du FPU comme
.IR fegetround (),
.IR fesetround (),
l'environnement en virgule flottante comme
.IR fegetenv (),
.IR feholdexcept (),
.IR fesetenv (),
.IR feupdateenv (),
et la gestion des exception comme
.IR feclearexcept (),
.IR fegetexceptflag (),
.IR feraiseexcept (),
.IR fesetexceptflag (),
.IR fetestexcept ().
.PP
Si l'accès direct au mot de commande du FPU est encore nécessaire, on peut
utiliser les macros _FPU_GETCW et _FPU_SETCW de
.IR /usr/include/fpu_control.h .
.SH "VOIR AUSSI"
.BR feclearexcept (3)
.br
.BR /usr/include/i386/fpu_control.h
.SH TRADUCTION
Christophe Blaess, 1998-2003.
