.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\" Traduction Christophe Blaess <ccb@club-internet.fr>
.\" 21/07/2003 - LDP-1.57
.TH CABS 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
cabs, cabsf, cabsl \- Modules de nombres complexes.
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BI "double cabs(double complex " z );
.sp
.BI "float cabsf(float double complex " z );
.sp
.BI "long double cabsl(long double complex " z );
.sp
.SH DESCRIPTION
Les fonctions de la famille
.BR cabs ()
renvoient le module du nombre complexe
.IR z ,
ce que certains appellent aussi "valeur absolue" de
.IR z .
.LP
Le résultat est un nombre réel.
.SH NOTE
Cette fonction est en fait un alias pour hypot(a,b)\ =\ sqrt(a*a+b*b).
.SH "CONFORMITÉ"
C99
.SH "VOIR AUSSI"
.BR abs (3),
.BR hypot (3),
.BR cimag (3),
.BR complex (5)
.SH TRADUCTION
Christophe Blaess, 2003.
