.\" Copyright 2002 Walter Harms(walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\" Traduction Christophe Blaess <ccb@club-internet.fr>
.\" 21/07/2003 - LDP-1.57
.\"
.TH CACOSH 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
cacosh, cacoshf, cacoshl \- Fonctions arguments cosinus hyperboliques complexes.
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BI "double complex cacosh(double complex " z ); 
.sp
.BI "float complex cacoshf(float complex double " z );
.sp
.BI "long double complex cacoshl(long double complex " z );
.sp
.SH DESCRIPTION
La fonction
.BR cacosh ()
calcule la version complexe de
.BR acosh ().
Si y\ =\ cacosh(z), alors z\ =\ ccosh(y).
La partie imaginaire de y est choisie dans l'intervalle [-pi*i,pi*i].
La partie réelle de y est positive ou nulle.
.LP
On a cacosh(z)\ =\ (0.5)*clog((1+z)/(1-z)).
.SH "CONFORMITÉ"
C99
.SH "VOIR AUSSI"
.BR cabs (3),
.BR cimag (3),
.BR acosh (3)
.SH TRADUCTION
Christophe Blaess, 2003.
