.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\" Traduction Christophe Blaess <ccb@club-internet.fr>
.\" 21/07/2003 - LDP-1.57
.\"
.TH CASINH 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
casinh, casinhf, casinhl \- Fonctions arguments sinus hyperboliques complexes.
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BI "double complex casinh(double complex " z ); 
.sp
.BI "float complex casinhf(float complex double " z );
.sp
.BI "long double complex casinhl(long double complex " z );
.sp
.SH DESCRIPTION
La fonction
.BR casinh ()
calcule la version complexe de
.BR asinh ().
Si y\ =\ casinh(z), alors z\ =\ csinh(y).
La partie imaginaire de y est choisie dans l'intervalle [-pi/2*i,pi/2*i].
.LP
On a casinh(z)\ =\ clog(z+csqrt(z*z+1)).
.SH "CONFORMITÉ"
C99
.SH "VOIR AUSSI"
.BR cabs (3),
.BR cimag (3),
.BR asinh (3)
.SH TRADUCTION
Christophe Blaess, 2003.
