.\" Copyright 2002 Walter Harms(walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\" Traduction Christophe Blaess <ccb@club-internet.fr>
.\" 21/07/2003 - LDP-1.57
.\"
.TH CATAN 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
catan, catanf, catanl \- Fonctions arc tangentes complexes.
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BI "double complex catan(double complex " z ); 
.sp
.BI "float complex catanf(float complex " z ); 
.sp
.BI "long double complex catanl(long double complex " z ); 
.sp
.SH DESCRIPTION
La fonction
.BR catan ()
calcule la version complexe de
.BR atan ().
Si y\ =\ catan(z), alors z\ =\ ctan(y).
La partie réelle de y est choisie dans l'intervalle [-pi/2,pi/2].
.LP
On a
catan(z)\ =\ 1/2i\ clog((1+iz)/(1-iz)).
.SH "CONFORMITÉ"
C99
.SH "VOIR AUSSI"
.BR clog (3),
.BR ccos (3)
.SH TRADUCTION
Christophe Blaess, 2003.
