.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\" Traduction Christophe Blaess <ccb@club-internet.fr>
.\" 21/07/2003 - LDP-1.57
.\"
.TH CATANH 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
catanh, catanhf, catanhl \- Fonctions arguments tangentes hyperboliques complexes.
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BI "double complex catanh(double complex " z ); 
.sp
.BI "float complex catanhf(float complex double " z );
.sp
.BI "long double complex catanhl(long double complex " z );
.sp
.SH DESCRIPTION
La fonction
.BR catanh ()
calcule la version complexe de
.BR atanh ().
Si y\ =\ catanh(z), alors z\ =\ ctanh(y).
La partie imaginaire de y est choisie dans l'intervalle [-pi/2*i,pi/2*i].
.LP
On a catanh(z)\ =\ 0.5*clog((1+z)/(1-z)).
.SH "CONFORMITÉ"
C99
.SH "VOIR AUSSI"
.BR cabs (3),
.BR cimag (3),
.BR atanh (3)
.SH TRADUCTION
Christophe Blaess, 2003.
