.\" Copyright 1995 Jim Van Zandt <jrv@vanzandt.mv.com>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" changed `square root' into `cube root' - aeb, 950919
.\"
.\" Modified 2002-07-27 Walter Harms
.\" (walter.harms@informatik.uni-oldenburg.de)
.\" Traduction Christophe Blaess <ccb@club-internet.fr>
.\" 21/07/2003 - LDP-1.57
.\"
.TH CBRT 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
cbrt, cbrtf, cbrtl \- Fonctions racines cubiques
.SH SYNOPSIS
.nf
.B #include <math.h>
.sp
.BI "double cbrt(double " x );
.sp 
.BI "float cbrtf(float " x );
.sp
.BI "long double cbrtl(long double " x );
.fi
.SH DESCRIPTION
La fonction
.BR cbrt ()
renvoie la racine cubique (réelle) de
.IR x .
La fonction ne peut pas échouer\ ; chaque valeur réelle possible a une
racine cubique calculable.
.SH "CONFORMITÉ"
.B cbrt()
était une extension GNU. C'est devenu une obligation C99.
.SH "VOIR AUSSI"
.BR sqrt (3),
.BR pow (3)
.SH TRADUCTION
Christophe Blaess, 1996-2003.
