.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\" Traduction Christophe Blaess <ccb@club-internet.fr>
.\" 21/07/2003 - LDP-1.57
.\" Màj 27/06/2005 LDP-1.60
.\"
.TH CEXP 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
cexp, cexpf, cexpl \- Fonctions exponentielles complexes.
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BI "double complex cexp(double complex " z ");"
.sp
.BI "float complex cexpf(float complex " z ");"
.sp
.BI "long double complex cexpl(long double complex " z ");"
.sp
.SH DESCRIPTION
Ces fonctions calculent e (2.71828..., la base des logarithmes népériens)
élevé à la puissance
.IR z .
.LP
On a cexp(I*z)\ =\ ccos(z) + I*csin(z).
.SH "CONFORMITÉ"
C99
.SH "VOIR AUSSI"
.BR cabs (3),
.BR cpow (3),
.BR clog (3)
.SH TRADUCTION
Christophe Blaess, 2003.
