.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\" Traduction Christophe Blaess <ccb@club-internet.fr>
.\" 21/07/2003 - LDP-1.57
.\" Màj 27/06/2005 LDP-1.60
.\"
.TH CIMAG 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
cimag, cimagf, cimagl \- Obtenir la partie imaginaire d'un nombre complexe.
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BI "double cimag(double complex " z ");"
.sp
.BI "float cimagf(float double complex " z ");"
.sp
.BI "long double cimagl(long double complex " z ");"
.sp
.SH DESCRIPTION
La fonction
.BR cimag ()
renvoie la partie imaginaire du nombre complexe
.IR z .
.LP
On a z\ =\ creal(z)\ +\ I*cimag(z).
.SH NOTE
Le compilateur gcc supporte également la macro
__imag__, c'est une extension GNU.
.SH "CONFORMITÉ"
C99
.SH "VOIR AUSSI"
.BR cabs (3),
.BR creal (3),
.BR complex (5)
.SH TRADUCTION
Christophe Blaess, 2003.
