.\" (c) 1993 by Thomas Koenig (ig25@rz.uni-karlsruhe.de)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" License.
.\" Modified Sat Jul 24 21:27:01 1993 by Rik Faith (faith@cs.unc.edu)
.\"
.\" Traduction 23/10/1996 par Christophe Blaess (ccb@club-internet.fr)
.\" màj 26/06/2000 LDP 1.30
.\" Mise à jour 04/06/2001 - LDP-man-pages-1.36
.\" MàJ 21/07/2003 LDP-1.56
.TH CLOCK 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
clock \- Déterminer la durée d'utilisation du processeur.
.SH SYNOPSIS
.nf
.B #include <time.h>
.sp
.B clock_t clock (void);
.fi
.SH DESCRIPTION
La fonction
.B clock()
renvoie une approximation de la durée écoulée d'utilisation du processeur
par le programme.
.SH "VALEUR RENVOYÉE"
La valeur renvoyée est le temps CPU écoulé, en unités d'horloge
.BR clock_t ,
pour obtenir une durée en secondes, divisez\-la par
.BR CLOCKS_PER_SEC .
Si l'heure processeur n'est pas disponible, ou si sa valeur ne peut pas
être représentée correctement, la valeur renvoyée est (clock_t)\-1.
.SH "CONFORMITÉ"
ANSI C.
POSIX demande que CLOCKS_PER_SEC soit égal à 1000000 indépendamment de
la résolution réelle.
.SH NOTES
Le standard C autorise une valeur quelconque d'horloge au début du programme,
il faut donc utiliser la différence entre la valeur actuelle et celle de
.B clock()
au lancement du programme pour obtenir une portabilité maximale.
.PP
Notez que la valeur peut revenir à zéro. Sur un système 32 bits, lorsque
CLOCKS_PER_SEC vaut 1000000, cette fonction redonnera les mêmes valeurs toutes
les 72 minutes environ.
.PP
Sur plusieurs autres implémentations,
la valeur renvoyée par
.BR clock ()
inclue aussi le temps écoulé pour l'exécution des processus fils dont les
statistiques ont été collectées lors d'un appel de la famille
.BR wait (2).
Linux n'inclut pas le temps des enfants attendus dans la
valeur renvoyée par
.BR clock ().
.\" I have seen this behaviour on Irix 6.3, and the OSF/1, HP/UX, and
.\" Solaris manual pages say that clock() also does this on those systems.
.\" POSIX 1003.1-2001 doesn't explicitly allow this, nor is there an
.\" explicit prohibition. -- MTK
La fonction
.BR times (),
qui renvoie de manière explicite et distinctes les informations sur l'appelant
et ses enfants peut être préférable.
.SH "VOIR AUSSI"
.BR getrusage (2),
.BR times (2)
.SH TRADUCTION
Christophe Blaess, 1996-2003.
