.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\" Traduction Christophe Blaess <ccb@club-internet.fr>
.\" 21/07/2003 - LDP-1.57
.\" Màj 13/06/2005 LDP-1.59
.\" Màj 27/06/2005 LDP-1.60
.\"
.TH CPOW 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
cpow, cpowf, cpowl \- Fonctions puissances complexes.
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BI "double complex cpow(double complex " x " ,complex double " z ");"
.sp
.BI "float complex cpowf(float complex " x " ,complex float " z ");"
.sp
.BI "long double complex cpowl(long double complex " x " ,complex long double " z ");"
.sp
.SH DESCRIPTION
Ces fonctions calculent x élevé à la puissance z.
(avec une coupure pour x appartenant à l'axe réel négatif.)
.SH "CONFORMITÉ"
C99
.SH "VOIR AUSSI"
.BR cabs (3),
.BR pow (3)
.SH TRADUCTION
Christophe Blaess, 2003.
