.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\" Traduction Christophe Blaess <ccb@club-internet.fr>
.\" 21/07/2003 - LDP-1.57
.\" Màj 27/06/2005 LDP-1.60
.\"
.TH CARG 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
cproj, cprojf, cprojl \- Projections sur une sphère de Riemann.
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BI "double complex cproj(double complex " z ");"
.sp
.BI "float complex cprojf(float complex " z ");"
.sp
.BI "long double complex cprojl(long double complex " z ");"
.sp
.SH DESCRIPTION
Ces fonctions permettent de projeter un point d'un plan sur la surface d'une
sphère de Riemann.
Chaque point complexe z fini se projette sur lui-même, chaque point
complexe ayant une composante infinie se projette en une valeur infinie
donnée\ : l'infini positif sur l'axe réel.
.SH "CONFORMITÉ"
C99
.SH "VOIR AUSSI"
.BR cabs (3)
.SH TRADUCTION
Christophe Blaess, 2003.

