.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\" Traduction Christophe Blaess <ccb@club-internet.fr>
.\" 21/07/2003 - LDP-1.57
.\" Màj 27/06/2005 LDP-1.60
.\" Màj 04/07/2005 LDP-1.61
.\"
.TH CSIN 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
csin, csinf, csinl \- Fonctions sinus complexes.
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BI "double complex csin(double complex " z ");"
.sp
.BI "float complex csinf(float complex " z );
.sp
.BI "long double complex csinl(long double complex " z ");"
.sp
.SH DESCRIPTION
La fonction sinus complexe
.BR csin ( z )
est définie ainsi\ :
(exp(i*z)-exp(-i*z))/(2*i).
.SH "CONFORMITÉ"
C99
.SH "VOIR AUSSI"
.BR cabs (3),
.BR ctan (3),
.BR csin (3)
.SH TRADUCTION
Christophe Blaess, 2003.
