.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\" Traduction Christophe Blaess <ccb@club-internet.fr>
.\" 21/07/2003 - LDP-1.57
.\" Màj 27/06/2005 LDP-1.60
.\"
.TH CSINH 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
csinh, csinhf, csinhl \- Fonctions sinus hyperboliques complexes.
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BI "double complex csinh(double complex " z ");"
.sp
.BI "float complex csinhf(float complex " z ");"
.sp
.BI "long double complex csinhl(long double complex " z ");"
.sp
.SH DESCRIPTION
La fonctions hyperbolique complexe
.BR sinh ( z )
est définie ainsi\ :
(exp(z)-exp(-z))/2.
.SH "CONFORMITÉ "
C99
.SH "VOIR AUSSI"
.BR cabs (3),
.BR ctanh (3),
.BR ccosh (3)
