.\"  Copyright 2001 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" aeb: some corrections
.\"
.\" Traduction 22/04/2002 par Stéphan Rafin (stephan.rafin@laposte.net)
.\" MàJ 21/07/2003 LDP-1.56
.\"
.TH DYSIZE 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
dysize \- Obtenir le nombre de jours pour une année donnée.
.SH SYNOPSIS
.sp
.BR "#define _BSD_SOURCE" "   /* ou bien : #define _SVID_SOURCE */
.br
.BR "#include <time.h>
.sp
.BI "int dysize(int " year );
.sp
.SH DESCRIPTION
La fonction renvoie 365 pour une année normale et 366 pour une année bissextile.
L'identification d'une année bissextile repose sur le calcul suivant :
.sp
(year) %4 == 0 && ((year) %100 != 0 || (year) %400 == 0)
.sp
La formule est définie dans la macro
.I __isleap(year)
que l'on trouve également dans 
.IR <time.h> .
.SH "CONFORMITÉ"
Cette fonction apparaît dans SunOS 4.x.
.SH NOTES
Il s'agit seulement d'une fonction à vocation de compatibilité. Ne l'utilisez pas dans de nouveaux programmes.
La version Unix SCO de cette fonction est affectée par le bug de l'an 2000.
.SH "VOIR AUSSI"
.BR strftime (3),
.BR time (3)
.SH TRADUCTION
Stéphan Rafin, 2002.
