.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single Unix specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.\" Traduction 28/08/2000 par Christophe Blaess (ccb@club-internet.fr)
.\" LDP 1.30
.\" Mise à jour 25/01/2002 - LDP-man-pages-1.47
.\" MàJ 21/07/2003 LDP-1.56
.TH FGETWS 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
fgetws \- Lire une chaîne de caractères larges depuis un flux.
.SH SYNOPSIS
.nf
.B #include <wchar.h>
.sp
.BI "wchar_t *fgetws (wchar_t *" ws ", int " n ", FILE *" stream );
.fi
.SH DESCRIPTION
La fonction \fBfgetws\fP est l'équivalent pour les caractères larges de la fonction \fBfgets\fP.
Elle lit une chaîne d'au plus \fIn-1\fP caractères larges dans le buffer de caractères larges pointés
par \fIws\fP, puis ajoute un caractère L'\\0' final. La lecture s'arrête dès qu'un caractère large de
saut de ligne a été rencontré, et stocké. Elle s'arrête aussi lorsque la fin du flux est atteinte.
.PP
Il est de la responsabilité du programmeur de s'assurer qu'il y a assez de place pour au moins
\fIn\fP caractères larges dans \fIwst\fP.
.PP
Pour une version de cette fonction ignorant les verrouillages, voir
.BR unlocked_stdio (3).
.SH "VALEUR RENVOYÉE"
La fonction \fBfgetws\fP, lorsqu'elle réussit, renvoie \fIws\fP. Si la fin du flux est atteinte, ou si
une erreur se produit, elle renvoie NULL.
.SH "CONFORMITÉ"
ISO/ANSI C, UNIX98
.SH NOTES
Le comportement de \fBfgetws\fP dépend de la catégorie LC_CTYPE de la localisation.
.PP
En l'absence d'information supplémentaire transmise à l'appel fopen(), on peut raisonnablement
supposer que \fBfgetws\fP lira en fait une chaîne multi-octets depuis le flux, et la convertira
en chaîne de caractères larges.
.PP
Cette fonction n'est pas fiable, car elle ne permet pas de traiter correctement les caractères larges nuls
susceptible d'être rencontrés en entrée.
.SH "VOIR AUSSI"
.BR fgetwc (3),
.BR unlocked_stdio (3)
.SH TRADUCTION
Christophe Blaess, 2000-2003.

