.\" Copyright (C) 2001 Andries Brouwer <aeb@cwi.nl>.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Traduction 25/04/2002 par Stéphan Rafin (stephan.rafin@laposte.net)
.\" MàJ 21/07/2003 LDP-1.56
.\"
.TH FPURGE 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
fpurge, __fpurge \- Purger un flux
.SH SYNOPSIS
.nf
/* non supporté */
.B #include <stdio.h>
.sp
.BI "int fpurge(FILE *" stream );
.sp
/* supporté */
.B #include <stdio.h>
.br
.B #include <stdio_ext.h>
.sp
.BI "void  __fpurge(FILE *" stream );
.fi
.SH DESCRIPTION
La fonction
.B fpurge()
efface les tampons d'un flux donné.
Pour les flux de sortie, on se débarrasse de toute sortie n'ayant pas encore été écrite.
Pour les flux d'entrée, on renonce à toute entrée lue par l'objet sous-jacent  
mais n'ayant pas encore été acquise par
.BR getc (3);
Cela inclut tout texte ré-injecté dans le flux par \fIungetc\fP(). Voir aussi
.BR fflush (3).
.LP
La fonction
.B __fpurge()
fait exactement la même chose mais n'a pas de code de retour.
.SH "VALEUR RENVOYÉE"
En cas de succès,
.B fpurge()
renvoie 0.
En cas d'erreur, elle renvoie \-1 et positionne
.I errno
de façon adéquate.
.SH ERREURS
.TP
.B EBADF
.I stream
ne correspond pas à un flux ouvert.
.SH "CONFORMITÉ"
Ces fonctions ne sont ni standards ni portables.
La fonction
.IR fpurge ()
a été introduite sous BSD 4.4 et n'est pas disponible sous Linux.
La fonction
.IR __fpurge ()
a été introduite sous solaris, et se trouve dans la glibc 2.1.95 et ses versions ultérieures.
.SH NOTES
Vouloir purger des tampons d'entrée constitue généralement une erreur.
.SH "VOIR AUSSI"
.BR fclean (3),
.BR fflush (3),
.BR setbuf (3),
.BR stdio_ext (3)
.SH TRADUCTION
Stéphan Rafin, 2002.
