.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.\" Modified 2003-11-18, aeb: historical remarks
.\"
.\" Màj 21/07/2003 LDP-1.56
.\" Màj 06/07/2005 LDP-1.62
.\" Màj 20/07/2005 LDP-1.64
.\"
.TH GAMMA 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
gamma, gammaf, gammal \- Logarithme de la fonction gamma.
.SH SYNOPSIS
.B #include <math.h>
.sp
.BI "double gamma(double " x ");"
.sp
.BI "float gammaf(float " x ");"
.sp
.BI "long double gammal(long double " x ");"
.sp
.SH DESCRIPTION
Pour la définition de la fonction Gamma, voir
.BR tgamma (3).
.PP
.SS "Versions BSD*"
La libm de BSD 4.4 et FreeBSD a une fonction
.B gamma()
qui calcule la fonction Gamma, comme on s'y attend.
.SS "Version GlibC"
La Glibc a une fonction
.B gamma()
qui est équivalente à
.B lgamma()
et qui calcule le logarithme naturel de la fonction Gamma.
(Ceci est seulement pour des raisons de compatibilité. N'utilisez pas
cette fonction.)
.SH HISTORIQUE
BSD 4.2 avait une fonction
.B gamma()
qui calculait
.RI ln(|Gamma(| x |)|),
laissant le signe de
.RI Gamma(| x |)
dans l'entier externe
.IR signgam .
Dans BSD 4.3, le nom a été modifié en
.BR lgamma() ,
et la page de manuel promettait\ :
.sp
.in +3
«\ Un jour où l'autre, le nom gamma sera réhabilité et utilisé pour la
fonction Gamma\ ».
.in
.sp
Cela est vraiment arrivé dans BSD 4.4 où
.B gamma()
calcule la fonction Gamma (sans effet sur
.IR signgam ).
Toutefois, cela est venu trop tard, et maintenant nous avons
.BR tgamma() ,
la vraie fonction gamma (Ndt\ : «\ true gamma\ »).
.\" The FreeBSD man page says about gamma() that it is like lgamma()
.\" except that is does not set signgam.
.\" Also, that 4.4BSD has a gamma() that computes the true gamma function.

.SH "CONFORMITÉ"
4.2BSD. Compatible avec de précédentes confusions.
.SH "VOIR AUSSI"
.BR lgamma (3),
.BR signgam (3),
.BR tgamma (3)
.SH TRADUCTION
.RI "Thierry Vignaud <" tvignaud@mandrakesoft.com ">, 2002"

Alain Portal, 2005
