.\" @(#)getrpcent.3n	2.2 88/08/02 4.0 RPCSRC; from 1.11 88/03/14 SMI
.\" MàJ 21/07/2003 LDP-1.56
.TH GETRPCENT 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
getrpcent, getrpcbyname, getrpcbynumber, setrpcent, endrpcent \- Lire une entrée RPC.
.SH SYNOPSIS
.nf
.ft B
#include <netdb.h>
.LP
.ft B
struct rpcent *getrpcent()
.LP
.ft B
struct rpcent *getrpcbyname(nom)
char *nom;
.LP
.ft B
struct rpcent *getrpcbynumber(nombre)
int nombre;
.LP
.ft B
setrpcent (stayopen)
int stayopen;
.LP
.ft B
endrpcent ()
.fi
.SH DESCRIPTION
.LP
.BR getrpcent() ,
.BR getrpcbyname() ,
et
.B getrpcbynumber()
renvoient chacune un pointeur sur un objet ayant la structure suivante et
contenant les champs d'une entrée de la base de données des programmes RPC
.BR /etc/rpc .
.RS
.LP
.nf
.ft B
struct	rpcent {
	char	*r_nom;	/* nom du serveur pour ce programme RPC */
	char	**r_aliases;	/* liste d'alias */
	long	r_nombre;	/* numéro de programme RPC */
};
.ft R
.fi
.RE
.LP
Les membres de cette structure sont:
.RS
.PD 0
.TP 20
.B r_nom
Le nom du serveur pour ce programme RPC.
.TP 20
.B r_aliases
Une liste d'alias (alias pour le programme RPC) terminée par un zéro.
.TP  20
.B r_nombre
Le numéro de programme RPC pour ce service.
.PD
.RE
.LP
.B getrpcent()
lit la ligne suivante du fichier, l'ouvrant si nécessaire.
.LP
.B getrpcent()
ouvre le fichier. Si le drapeau
.I stayopen
est non-nul, la base de données restera ouverte entre les appels
.B getrpcent()
(directs, ou indirects par l'un des autres appels
\*(lqgetrpc\*(rq).
.LP
.B endrpcent
ferme le fichier.
.LP
.B getrpcbyname()
et
.B getrpcbynumber()
recherchent séquentiellement depuis le début du fichier jusqu'à ce qu'un
nom ou un numéro de programme RPC faisant l'affaire soit trouvé ou jusqu'à la
fin du fichier.
.SH FICHIERS
.PD 0
.TP 20
.B /etc/rpc
.PD
.SH "VOIR AUSSI"
.BR rpc (5),
.BR rpcinfo (8C),
.BR ypserv (8)
.SH DIAGNOSTICS
.LP
Un pointeur
.SM NULL
est renvoyé à la fin du fichier
.SM (EOF)
ou en cas d'erreur.
.SH BOGUES
.LP
Toutes les informations sont stockées dans une zone statique et doivent donc
être copiées si on désire les conserver.

.SH TRADUCTION
.RI "Thierry Vignaud <" tvignaud@mandrakesoft.com ">, 1999"
.br
Christophe Blaess, 2003.
