.\" @(#)getrpcport.3r	2.2 88/08/02 4.0 RPCSRC; from 1.12 88/02/26 SMI
.\" MàJ 21/07/2003 LDP-1.56
.TH GETRPCPORT 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
getrpcport \- Renvoie un numéro de port RPC.
.SH SYNOPSIS
.ft B
.nf
int getrpcport(host, prognum, versnum, proto)
	char *host;
	int prognum, versnum, proto;
.fi
.SH DESCRIPTION
.B getrpcport()
renvoie le numéro de port pour la version
.I versnum
du programme RPC
.I prognum
qui fonctionne sur la machine
.I host
et utilisant le protocole
.IR proto .
.SH "VALEUR RENVOYÉE"
0 est renvoyé s'il n'est
.B pas
possible de contacter le portmapper, ou si
.I prognum
n'est pas déclaré. Si
.I prognum
est déclaré mais la version
.IR versnum ,
n'est pas celle employée, un numéro de port sera bien renvoyé, indiquant que le
programme est bien enregistré. L'erreur de version ne sera détectée qu'au
premier appel à ce service.

.SH TRADUCTION
.RI "Thierry Vignaud <" tvignaud@mandrakesoft.com ">, 1999"
