.\" Copyright 2000 Sam Varshavchik <mrsam@stop.mail-abuse.org>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References: RFC 2553
.\" Traduction 31/08/2000 par Christophe Blaess (ccb@club-internet.fr)
.\" LDP 1.31
.\" Mise à jour 06/06/2001 - LDP-man-pages-1.36
.\" MàJ 21/07/2003 LDP-1.56
.TH INET_NTOP 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
inet_ntop \- Manipuler les adresses réseau.
.SH SYNOPSIS
.nf
.B #include <sys/types.h>
.B #include <sys/socket.h>
.B #include <arpa/inet.h>
.sp
.BI "const char *inet_ntop(int " af ", const void * " src ,
.BI "                        char * " dst ", size_t " cnt );
.fi
.SH DESCRIPTION
Cette fonction convertit une adresse réseau représentée par  la structure
.I src
de la famille
.IR af ,
en une chaîne de caractères copiée dans le buffer
.IR dst ,
long de
.I cnt
octets.
.PP
.BR inet_ntop (3)
étend les possibilités de la fonction
.BR inet_ntoa (3)
pour gérer plusieurs familles d'adresses.
L'utilisation de
.BR inet_ntoa (3)
est à présent déconseillée au profit de
.BR inet_ntop (3).
Les familles d'adresses suivantes sont supportées dès à présent :
.TP
.B AF_INET
.I src
doit pointer sur une structure
.I struct in_addr
(octets stockés dans l'ordre du réseau)
qui est convertie en une adresse réseau IPv4 dans le
format décimal pointé "\fIddd.ddd.ddd.ddd\fP".
Le buffer 
.I dst
doit mesurer au minimum
.B INET_ADDRSTRLEN
octets.
.TP
.B AF_INET6
.I src
doit pointer sur une structure
.IR "struct in6_addr"
(octets stockés dans l'ordre du réseau)
qui est convertie dans la représentation la plus appropriée de
l'adresse IPv6.
Le buffer
.I dst
doit mesurer au minimum
.B INET6_ADDRSTRLEN
octets.
.SH "VALEUR RENVOYÉE"
.B inet_ntop
renvoie un pointeur sur
.IR buf .
Si une erreur se produit, la fonction renvoie NULL, et
.I errno
contient
.B EAFNOSUPPORT
si
.I af
ne représente pas une famille d'adresses valide,
ou
.B ENOSPC
si l'adresse convertie ne tient pas dans le buffer
.IR dst ,
dont la taille est indiquée par l'argument
.IR cnt .
.SH "VOIR AUSSI"
.BR inet_pton (3)
.SH BOGUES
.B AF_INET6
convertit les adresse IPv4 projetées dans l'espace IPv6 en
employant le format IPv6.
.SH TRADUCTION
Christophe Blaess, 2000-2003.
