.\" peter memishian -- meem@gnu.ai.mit.edu
.\" $Id: insque.3,v 1.2 1996/10/30 21:03:39 meem Exp meem $
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"   Linux libc source code (5.4.7)
.\"   Solaris 2.x, OSF/1, and HP-UX manpages
.\"   Curry's "UNIX Systems Programming for SVR4" (O'Reilly & Associates 1996)
.\"
.\"
.\"
.\" Traduction 22/11/1996 par Christophe Blaess (ccb@club-internet.fr)
.\" Mise à jour 01/11/1999
.\" MàJ 21/07/2003 LDP-1.56
.TH INSQUE 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
insque, remque \- Ajouter ou supprimer un élément d'une file.
.SH SYNOPSIS
.nf
.B #include <search.h>
.sp
.BI "void insque (struct qelem *" elem ", struct qelem *" prev );
.BI "void remque (struct qelem *" elem );
.SH DESCRIPTION
Les fonctions \fBinsque()\fP et \fBremque()\fP permettent de manipuler une
file constituée d'une liste doublement chaînée. Chaque élément de cette liste
est du type \fBstruct qelem\fP

La structure \fBqelem\fP est définie ainsi\ :

.RS
.nf
struct qelem {
    struct    qelem *q_forw;
    struct    qelem *q_back;
    char      q_data[1];
};
.fi
.RE

\fBinsque()\fP insère l'élément pointé par \fIelem\fP immédiatement
après l'élément pointé par \fIprev\fP, qui ne doit \fBJAMAIS\fP être NULL.

\fBremque()\fP supprime l'élément pointé par \fIelem\fP de la liste doublement
chaînée.
.SH "CONFORMITÉ"
SVR4
.SH BOGUES
Le champ  q_data peut parfois être défini comme un \fBchar *\fP, et sous
solaris 2.x, il n'existe pas.

L'emplacement des prototypes de ces fonctions varie suivant les différentes
versions d'Unix. Certains systèmes les placent dans <search.h>, d'autres dans
<string.h>. La bibliothèque GlibC les place dans <search.h>.

Quelques versions d'UNIX (comme HP-UX 10.x) ne définissent pas une 
\fBstruct qelem\fP mais utilisent à la place des arguments de
\fBinsque()\fP et \fBremque()\fP du type \fBvoid *\fP.

.SH TRADUCTION
Christophe Blaess, 1996-2003.
