.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single Unix specification http://www.UNIX-systems.org/online.html
.\"
.\" Modified, aeb, 990824
.\"
.\" Traduction 04/01/2000 par Christophe Blaess (ccb@club-internet.fr)
.\" LDP-man-pages 1.28
.\" MàJ 21/07/2003  LDP-1.56
.TH MB_LEN_MAX 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
MB_LEN_MAX \- Longueur maximale d'un caractère quelque soit la localisation.
.SH SYNOPSIS
.nf
.B #include <limits.h>
.fi
.SH DESCRIPTION
La macro
.B MB_LEN_MAX
est la limite supérieure au nombre d'octets nécessaires pour représenter un
caractère large unique, quelque soit la localisation choisie.
.SH "VALEUR RENVOYEÉ"
Une constante entière >= 1.
.SH "CONFORMITÉ"
ANSI C, POSIX.1
.SH NOTES
Les deux entités
.B MB_LEN_MAX
et
.B sizeof(wchar_t)
n'ont aucun rapport. Dans la bibliothèque GlibC
.B MB_LEN_MAX
vaut typiquement 6 alors que
.B sizeof(wchar_t)
vaut 4.
.SH "VOIR AUSSI"
.BR MB_CUR_MAX (3)
.SH TRADUCTION
Christophe Blaess, 2000-2003.

