.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\" Based on glibc infopages
.\"
.\" Corrections by aeb
.\" MàJ 21/07/2003 LDP-1.56
.TH  NAN 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
nan, nanf, nanl \- Fonctions renvoyant «\ Not a Number\ ».
.SH SYNOPSIS
.B #include <math.h>
.sp
.BI "double nan(const char *" tagp );
.sp
.BI "float nanf(const char *" tagp );
.sp
.BI "long double nanl(const char *" tagp );
.SH DESCRIPTION
Ces fonctions renvoient une représentation (déterminée par
.IR tagp )
d'un NaN (Not-A-Number, élément non-numérique indiquant un cas d'erreur dans
les routines mathématiques).
 Si cette implementation ne supporte pas support les NaNs,
ces fonctions renvoient zéro.
.LP
L'appel
.I nan("char-sequence")
est équivalent à
.IR strtod ("NAN(char-sequence)",NULL) " ;"
de même
.I nanf
et
.I nanl
sont équivalentes aux appels analogues 
.I strtof
et
.IR strtold .
.PP
L'argument
.I tagp
est utilisé de manière non spécifiée.  Sur les systèmes IEEE 754, il
existe de nombreuses représentations de NaN, et
.I tagp
en sélectionne une.  Sur les autres systèmes, il peut n'avoir aucun effet.
.SH "CONFORME À"
C99. Voir aussi IEC 559 et l'annexe sur les fonctions recommendées dans
 IEEE 754/IEEE 854.
.SH "VOIR AUSSI"
.BR isnan (3),
.BR strtod (3)
.SH TRADUCTION
.RI "Thierry Vignaud <" tvignaud@mandrakesoft.com ">, 2002"
.br
Christophe Blaess, 2003.
