.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Modified Fri Jun 23 01:35:19 1995 Andries Brouwer <aeb@cwi.nl>
.\" (prompted by Bas V. de Bakker <bas@phys.uva.nl>)
.\" Corrected (and moved to man3), 980612, aeb
.\" Traduction 14/12/1998 par Christophe Blaess (ccb@club-internet.fr)
.\" LDP man-pages 1.21
.\" MàJ 21/07/2003 LDP-1.56
.TH PROFIL 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
profil \- Suivi du temps d'exécution.
.SH SYNOPSIS
.B #include <unistd.h>
.sp
.BI "int profil(u_short *" buffer ", size_t " taille_buf ", size_t " offset ", u_int " echelle );
.SH DESCRIPTION
Cette routine fournit un moyen de détecter les zones où votre programme
passe l'essentiel de son temps. L'argument
.I buffer
pointe sur
.I taille_buf
octets de mémoire. Toutes les 10 millisecondes virtuelles, le compteur
de programme (PC) est examiné. On lui soustrait la valeur
.I offset
et le résultat est multiplié par 
.IR echelle
puis divisé par 65536.
Si la valeur résultant est inférieure a
.IR taille_buff ,
alors l'élément correspondant du
.I buffer
est incrémenté.
Si
.I buffer
est NULL, Le suivi est désactivé.
.SH "VALEUR RENVOYÉE"
Cette routine renvoie toujours zéro.
.SH BOGUES
.B profil
ne doit pas être invoqué dans les programmes qui
utilisent des timers
.BR ITIMER_PROF .

Un vrai suivi fourni par le noyau donnerait des résultats plus précis.
La bibliothèque Libc 4.4 contenait un patch pour implémenter un
appel système profil dans le noyau.
.SH "CONFORMITÉ"
Similaire à un appel de SVr4 (mais pas POSIX.1).
.SH "VOIR AUSSI"
.BR gprof (1),
.BR setitimer (2),
.BR signal (2),
.BR sigaction (2).

.SH TRADUCTION
Christophe Blaess, 1998-2003.
