.\" Copyright (C), 1995, Graeme W. Wilford. (Wilf.)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Wed Jun 14 16:10:28 BST 1995 Wilf. (G.Wilford@@ee.surrey.ac.uk)
.\"
.\"
.\" Traduction 05/11/1996 par Christophe Blaess (ccb@club-internet.fr)
.\" MàJ 21/07/2003 LDP-1.56
.\"
.TH RE_COMP 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
re_comp, re_exec \- Fonction regex BSD.
.SH SYNOPSIS
.B #include <sys/types.h>
.br
.B #include <regex.h>
.sp
.BI "char *re_comp (char *" regex );
.br
.BI "int re_exec (char *" string );
.SH DESCRIPTION
La fonction
.B re_comp
permet de compiler une expression régulière, terminée par un caractère nul,
et pointée par
.IR regex .
Le motif compilé occupe une zone de mémoire statique, le buffer de motif,
qui sera ecrasée par un autre appel à
.BR re_comp .
Si
.I regex
vaut
.BR NULL ,
rien n'est effectué, et le contenu du buffer de motif n'est pas altéré.

.B re_exec
est utilisé pour verifier si la chaîne terminée par un caractère nul, pointée
par
.I string
correspond au motif précédemment compilé par
.IR regex .
.SH "VALEUR RENVOYÉE"
.B re_comp
renvoie
.B NULL
s'il peut compiler correctement
.IR regex,
sinon, il renvoie un pointeur sur le message d'erreur approprié.

.B re_exec
renvoie 1 si la correspondance est exacte, zéro si elle échoue.
.SH "CONFORMITÉ"
BSD 4.3
.SH "VOIR AUSSI"
.BR regex (7),
.B "Manuel regex GNU"
.SH TRADUCTION
Christophe Blaess, 1996-2003.
