.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL, 2002-07-27 Walter Harms
.\" Traduction Christophe Blaess <ccb@club-internet.fr>
.\" 30/07/2003 LDP-1.58
.\" Màj 20/07/2005 LDP-1.64
.\"
.TH SINCOS 3 "30 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
sincos, sincosf, sincosl \- Calculer simultanément des sinus et cosinus.
.SH SYNOPSIS
.nf
.B #include <math.h>
.sp
.BI "double sincos(double " x ", double *" sin ", double *" cos );
.sp
.BI "float sincosf(float " x ", float *" sin ", float *" cos );
.sp
.B "long double"
.BI "sincosl(long double " x ", long double *" sin ", long double *" cos );
.fi
.SH DESCRIPTION
De nombreuses applications ont besoin de calculer le sinus et le cosinus
du même angle
.IR x .
Cette fonction calcule les deux en même temps, et stocke les résultats
dans les pointeurs fournis.
.SH "CONFORMITÉ"
Cette fonction est une extension GNU.
.SH "VOIR AUSSI"
.BR sin (3),
.BR cos (3),
.BR tan (3)
.SH TRADUCTION
Christophe Blaess, 2003.
