.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 18:11:47 1993 by Rik Faith (faith@cs.unc.edu)
.\"
.\" Traduction 09/11/1996 par Christophe Blaess (ccb@club-internet.fr)
.\" Màj 21/07/2003 LDP-1.56
.\" Màj 04/07/2005 LDP-1.61
.\"
.TH STRCAT 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
strcat, strncat \- Concaténer deux chaînes.
.SH SYNOPSIS
.nf
.B #include <string.h>
.sp
.BI "char *strcat (char *" dest ", const char *" src );
.sp
.BI "char *strncat (char *" dest ", const char *" src ", size_t " n );
.fi
.SH DESCRIPTION
La fonction \fBstrcat()\fP ajoute la chaîne \fIsrc\fP à la fin de la chaîne
\fIdest\fP en écrasant le caractère «\ \e0\ » à la fin de
\fIdest\fP, puis en ajoutant un nouveau caractère «\ \e0\ » final. Les chaînes
ne doivent pas se chevaucher, et la chaîne \fIdest\fP doit être assez grande
pour accueillir le résultat.
.PP
La fonction \fBstrncat()\fP est identique, à la différence qu'elle ne copie
que les \fIn\fP premiers caractères de \fIsrc\fP à la fin de \fIdest\fP.
.SH "VALEUR RENVOYÉE"
Les fonctions \fBstrcat()\fP et \fBstrncat()\fP renvoient un pointeur
sur la chaîne résultat \fIdest\fP.
.SH "CONFORMITÉ"
SVID 3, POSIX, BSD 4.3, ISO 9899
.SH "VOIR AUSSI"
.BR bcopy (3),
.BR memccpy (3),
.BR memcpy (3),
.BR strcpy (3),
.BR strncpy (3),
.BR wcscat (3),
.BR wcsncat (3)
.SH TRADUCTION
Christophe Blaess, 1996-2003.
