.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 18:12:45 1993 by Rik Faith (faith@cs.unc.edu)
.\"
.\" Traduction 09/11/1996 par Christophe Blaess (ccb@club-internet.fr)
.\" Màj 21/07/2003 LDP-1.56
.\" Màj 04/07/2005 LDP-1.61
.\"
.TH STRCASECMP 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
strcasecmp, strncasecmp \- Comparer deux chaînes en ignorant les différences majuscules/minuscules.
.SH SYNOPSIS
.nf
.B #include <string.h>
.sp
.BI "int strcasecmp (const char *" s1 ", const char *" s2 );
.sp
.BI "int strncasecmp (const char *" s1 ", const char *" s2 ", size_t " n );
.fi
.SH DESCRIPTION
La fonction \fBstrcasecmp()\fP compare les deux chaînes \fIs1\fP et
\fIs2\fP, en ignorant les différences entre majuscules et minuscules.
Elle renvoie un entier négatif, nul, ou positif, si la
chaîne \fIs1\fP est respectivement inférieure, égale ou supérieure à \fIs2\fP.
.PP
La fonction \fBstrncasecmp()\fP est similaire, à la difference qu'elle ne
prend en compte que les \fIn\fP premiers caractères de \fIs1\fP.
.SH "VALEUR RENVOYÉE"
Les fonctions \fBstrcasecmp()\fP et \fBstrncasecmp()\fP renvoient un entier
inférieur, égal ou supérieur à zéro si \fIs1\fP (ou éventuellement ses
\fIn\fP premiers octets) est inférieure, égale ou supérieure à \fIs2\fP.
.SH "CONFORMITÉ"
BSD 4.4
.SH "VOIR AUSSI"
.BR bcmp (3),
.BR memcmp (3),
.BR strcmp (3),
.BR strcoll (3),
.BR strncmp (3),
.BR wcscasecmp (3),
.BR wcsncasecmp (3)
.SH TRADUCTION
Christophe Blaess, 1996-2003.
