.\" Copyright (c) 2003 Andries Brouwer (aeb@cwi.nl)
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\" Traduction : Alain Portal
.\" 04/07/2005 LDP-1.61
.\" Màj 14/12/2005 LDP-1.65
.\"
.TH STRTOIMAX 3 "1er novembre 2003" LDP "Manuel du programmeur Linux"
.SH "NOM"
strtoimax, strtoumax \- Convertir une chaîne de caractères en entier.
.SH SYNOPSIS
.nf
.B #include <inttypes.h>
.sp
.BI "intmax_t strtoimax (const char *" nptr ", char **" endptr ", int " base );
.br
.BI "uintmax_t strtoumax (const char *" nptr ", char **" endptr ", int " base );
.fi
.SH DESCRIPTION
Ces fonctions sont similaires à
.B strtol()
et
.BR strtoul() ,
excepté qu'elles retournent respectivement une valeur de type
.B intmax_t
et
.BR uintmax_t .
.SH "CONFORMITÉ"
C99, POSIX 1003.1-2003.
.SH "VOIR AUSSI"
.BR imaxabs (3),
.BR imaxdiv (3),
.BR strtol (3),
.BR strtoul (3),
.BR wcstoimax (3)
.SH TRADUCTION
.PP
Ce document est une traduction réalisée par Alain Portal
<aportal AT univ-montp2 DOT fr> le 4 juillet 2005
et révisée le 14 décembre 2005.
.PP
L'équipe de traduction a fait le maximum pour réaliser une adaptation
française de qualité. La version anglaise la plus à jour de ce document est
toujours consultable via la commande\ : «\ \fBLANG=en\ man\ 3\ strtoimax\fR\ ».
N'hésitez pas à signaler à l'auteur ou au traducteur, selon le cas, toute
erreur dans cette page de manuel.
