.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 17:52:15 1993 by Rik Faith (faith@cs.unc.edu)
.\"
.\" Traduction 10/11/1996 par Christophe Blaess (ccb@club-internet.fr)
.\" Modif C.Blaess 20/11/98 (string.h -> unistd.h)
.\" Mise à jour 26/01/2002 - LDP-man-pages-1.47
.\" MàJ 21/07/2003 LDP-1.56
.TH SWAB 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
swab \- Echanger des octets adjacents.
.SH SYNOPSIS
.nf
.B #include <unistd.h>
.sp
.BI "void swab (const void * " from ", void * " to ", size_t " n );
.fi
.SH DESCRIPTION
La fonction \fBswab()\fP copie \fIn\fP octets de la chaîne pointée par
\fIfrom\fP dans la chaine pointée par \fIto\fP, en échangeant les
octets adjacents de rangs pairs et impairs.
Cette fonction permet de transmettre des données entre des machines
qui utilisent des ordres poids fort/poids faible différents.
.LP
Cette fonction ne fait rien si \fIn\fP est négatif. Lorsque
\fIn\fP est positif et impair, elle manipule \fIn\fP-1 octets comme
décrit plus haut, et agit de manière non précisée avec le dernier octet.
Autrement dit, \fIn\fP doit être pair\ !)
.SH "VALEUR RENVOYÉE"
La fonction \fBswab()\fP ne renvoie pas de valeur.
.SH "CONFORMITÉ"
SVID 3, BSD 4.3, POSIX 1003.1-2001
.SH "VOIR AUSSI"
.BR bstring (3)
.SH TRADUCTION
Christophe Blaess, 1996-2003.
