.\" Copyright (C) 2002 Andries Brouwer <aeb@cwi.nl>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" Traduction Christophe Blaess, <ccb@club-internet.fr>
.\" MàJ 21/07/2003 LDP-1.56
.TH TCGETSID 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
tcgetsid \- Obtenir l'identificateur de session.
.SH SYNOPSIS
.sp
.BR "#include <termios.h>"
.sp
.BI "pid_t tcgetsid(int " fd );
.SH DESCRIPTION
La fonction
.B tcgetsid()
renvoie l'ID de la session en cours ayant le terminal associé
à
.I fd
comme terminal de contrôle..
Ce terminal doit être le terminal de contrôle du processus appelant.
.SH "VALEUR RENVOYÉE"
Si
.I fd
correspond au terminal de contrôle de notre session,
la fonction
.B tcgetsid()
renverra l'ID de cette session.
Sinon, elle renverra \-1, et remplira
.I errno
avec le code d'erreur.
.SH ERREURS
.TP
.B EBADF
.I fd
n'est pas un descripteur correct.
.TP
.B ENOTTY
Le processus n'a pas de terminal de contrôle, ou il en a un mais
ce n'est pas celui décrit par
.IR fd .
.SH NOTES
Cette fonction est implémentée via l'ioctl TIOCGSID, présent
depuis Linux 2.1.71.
.SH "CONFORMITÉ"
POSIX.1-2001.
.SH "VOIR AUSSI"
.BR getsid (2)
.SH TRADUCTION
Christophe Blaess, 2003.
