.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 17:46:57 1993 by Rik Faith (faith@cs.unc.edu)
.\"
.\" Traduction 10/11/1996 par Christophe Blaess (ccb@club-internet.fr)
.\" Mise à jour 26/01/2002 - LDP-man-pages-1.47
.\" MàJ 21/07/2003 LDP-1.56
.TH TMPFILE 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
tmpfile \- Créer un fichier temporaire.
.SH SYNOPSIS
.nf
.B #include <stdio.h>
.sp
.B FILE *tmpfile (void);
.fi
.SH DESCRIPTION
La fonction \fBtmpfile()\fP crée un nom de fichier unique.  
Le fichier temporaire est ouvert en lecture/écriture binaire (mode w+b).
Le fichier sera automatiquement détruit lors de sa fermeture, ou lorsque
le programme se terminera normalement.
.SH "VALEUR RENVOYÉE"
La fonction \fBtmpfile()\fP renvoie un pointeur de flux, ou NULL
si la création du fichier temporaire est impossible, auquel cas
\fIerrno\fP indique l'erreur.
.SH "ERREURS"
.TP 
.B EACCES
Autorisation de parcours refusée dans un répertoire du chemin d'accès.
.TP
.B EEXIST
Impossible de créer un nom de fichier unique.
.TP
.B EMFILE
Trop de descripteurs de fichiers pour le processus.
.TP
.B ENFILE
Trop de fichiers ouverts sur le système.
.TP
.B ENOSPC
Pas assez de place dans le répertoire pour ajouter un fichier.
.TP
.B EROFS
Système de fichiers en lecture seule.
.TP
.B EINTR
L'appel a été interrompu par un signal.
.SH "CONFORMITÉ"
SVID 3, POSIX, BSD 4.3, ISO 9899, SUSv2
.SH NOTES
Un message d'erreur peut être écrit sur \fIstdout\fP si le flux ne
peut pas être ouvert. ([NDT] \fIstdout\fP\ ? sûr\ ? ce ne serait
pas \fIstderr\fP plutôt\ ?).
.LP
Le standard ne précise pas le répertoire employé par \fItmpfile()\fP.
La GlibC essayera d'utilise le préfixe \fIP_tmpdir\fP défini
dans \fI<stdio.h>\fP, puis \fI/tmp\fP en cas d'échec.
.SH "VOIR AUSSI"
.BR mktemp (3),
.BR mkstemp (3),
.BR tmpnam (3),
.BR tempnam (3)
.SH TRADUCTION
Christophe Blaess, 1996-2003.
