.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single Unix specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.\" Traduction 29/08/2000 par Christophe Blaess (ccb@club-internet.fr)
.\" LDP 1.30
.\" MàJ 21/07/2003 LDP-1.56
.TH WCRTOMB 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
wcrtomb \- Convertir un caractère large en séquence multi-octets.
.SH SYNOPSIS
.nf
.B #include <wchar.h>
.sp
.BI "size_t wcrtomb (char *" s ", wchar_t " wc ", mbstate_t *" ps );
.fi
.SH DESCRIPTION
L'utilisation principale de cette fonction est le cas où \fIs\fP est non NULL, et \fIwc\fP n'est pas L'\\0'.
Alors, la fonction \fBwcrtomb\fP convertit le caractère large \fIwc\fP dans sa représentation multi-octets, et
l'enregistre au début de la chaîne pointée par \fIs\fP. Elle met à jour l'état de conversion \fI*ps\fP, et renvoie
la longueur de la représentation multi-octets, c'est à dire le nombre d'octets écrits en \fIs\fP.
.PP
Une autre possibilité peut se présenter quand \fIs\fP est non NULL, mais \fIwc\fP vaut L'\\0'. 
Dans cette situation la fonction \fBwcrtomb\fP enregistre dans la chaîne de caractères pointée par \fIs\fP la séquence
de décalages nécessaire pour ramener \fI*ps\fP à son état initial, suivie d'un caractère '\\0'.
Elle met à jour l'état \fI*ps\fP (le ramène donc à l'état initial), et renvoie la longueur de la séquence en ajoutant
un pour compter le caractère nul final.
.PP
Un troisième cas se présente quand \fIs\fP est NULL. Alors, \fIwc\fP est ignoré, et la fonction renvoie alors le résultat
de wcrtomb(buf,L'\\0',\fIps\fP) où buf est un buffer interne.
.PP
Dans tous les cas, si \fIps\fP est un pointeur NULL, un état statique interne est utilisé.
.SH "VALEUR RENVOYÉE"
La fonction \fBwcrtomb\fP renvoie le nombre d'octets qui ont été - ou qui auraient été - écrits dans \fIs\fP.
Si \fIwc\fP ne peut pas être représenté comme une séquence multi-octets (dans la localisation en cours), elle
renvoie (size_t)(-1), et place \fBEILSEQ\fP dans \fBerrno\fP .
.SH "CONFORMITÉ"
ISO/ANSI C, UNIX98
.SH "VOIR AUSSI"
.BR wcsrtombs (3)
.SH NOTES
Le comportement de \fBwcrtomb\fP dépend de la catégorie LC_CTYPE de la localisation.
.PP
L'utilisation d'un pointeur NULL pour \fIps\fP n'est pas sûre dans un contexte multithreads.
.SH TRADUCTION
Christophe Blaess, 2000-2003.
