.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single Unix specification http://www.UNIX-systems.org/online.html
.\"
.\" Traduction 29/08/2000 par Christophe Blaess (ccb@club-internet.fr)
.\" LDP 1.30
.\" Màj 21/07/2003 LDP-1.56
.\" Màj 04/07/2005 LDP-1.61
.\"
.TH WCSDUP 3 "1er novembre 2003" LDP "Manuel du programmeur Linux"
.SH NOM
wcsdup \- Dupliquer une chaîne de caractères larges.
.SH SYNOPSIS
.nf
.B #define _GNU_SOURCE
.br
.B #include <wchar.h>
.sp
.BI "wchar_t *wcsdup (const wchar_t *" s );
.fi
.SH DESCRIPTION
La fonction \fBwcsdup\fP est l'équivalent pour caractères larges de la fonction \fBstrdup\fP.
Elle alloue et renvoie une nouvelle chaîne de caractères larges dont le contenu initial est
une copie de la chaîne pointée par \fIs\fP.
.PP
La mémoire nécessaire est obtenue grâce à \fBmalloc\fP(3), et peut (doit) être libéré avec \fBfree\fP(3).
.SH "VALEUR RENVOYÉE"
La fonction \fBwcsdup\fP renvoie un pointeur sur la nouvelle chaîne de caractères larges, ou NULL s'il n'y avait
pas assez de mémoire disponible.
.SH ERREURS
.TP
.B ENOMEM
mémoire disponible insuffisante pour allouer la duplication de la chaîne.
.SH "CONFORMITÉ"
Cette fonction est une extension GNU.
+.\" présente dans la libc5 et glibc 2.0 et suivantes
.SH "VOIR AUSSI"
.BR strdup (3),
.BR wcscpy (3)
.SH TRADUCTION
Christophe Blaess, 2000-2003.
