.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single Unix specification http://www.UNIX-systems.org/online.html
.\"
.\" Traduction 29/08/2000 par Christophe Blaess (ccb@club-internet.fr)
.\" LDP 1.30
.\" MàJ 21/07/2003 LDP-1.56
.TH WCSNLEN 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
wcsnlen \- Déterminer la longueur d'une chaine de caractères larges limitée.
.SH SYNOPSIS
.nf
.B #include <wchar.h>
.sp
.BI "size_t wcsnlen (const wchar_t *" s ", size_t " maxlen );
.fi
.SH DESCRIPTION
La fonction \fBwcsnlen\fP est l'équivalent pour les caractères larges de la fonction \fBstrnlen\fP.
Elle renvoie le nombre de caractères larges se trouvant dans la chaînes pointée par \fIs\fP, sans compter le
caractère  L'\\0' final, en se limitant au maximum à \fImaxlen\fP caractères.
Pour ce faire, \fBwcsnlen\fP n'examine que les \fImaxlen\fP premiers caractères larges de \fIs\fP et jamais
au-delà de \fIs+maxlen\fP.
.SH "VALEUR RENVOYÉE"
La fonction \fBwcsnlen\fP renvoie \fIwcslen(s)\fP, si cette valeur est inférieure à \fImaxlen\fP, ou \fImaxlen\fP
si elle n'a pas rencontré de caractère L'\\0' en examinant les \fImaxlen\fP premiers caractères larges pointés par \fIs\fP.
.SH "CONFORMITÉ"
Cette fonction est une extension GNU.
.SH "VOIR AUSSI"
.BR strnlen (3),
.BR wcslen (3)
.SH TRADUCTION
Christophe Blaess, 2000-2003.
