.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single Unix specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.\" Traduction 29/08/2000 par Christophe Blaess (ccb@club-internet.fr)
.\" LDP 1.30
.\" MàJ 21/07/2003 LDP-1.56
.TH WCSPBRK 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
wcspbrk \- Rechercher un ensemble de caractères larges dans une chaîne.
.SH SYNOPSIS
.nf
.B #include <wchar.h>
.sp
.BI "wchar_t *wcspbrk (const wchar_t *" wcs ", const wchar_t *" accept );
.fi
.SH DESCRIPTION
La fonction \fBwcspbrk\fP est l'équivalent pour les caractères larges de la fonction \fBstrpbrk\fP.
Elle recherche la première occurence d'un caractère large se trouvant dans \fIaccept\fP au sein
de la chaîne \fIwcs\fP.
.SH "VALEUR RENVOYÉE"
La fonction \fBwcspbrk\fP renvoie un pointeur sur la première occurence au sein de \fIwcs\fP d'un caractère
large contenu dans \fIaccept\fP. Si  \fIwcs\fP n'en contient aucun, elle renvoie NULL.
.SH "CONFORMITÉ"
ISO/ANSI C, UNIX98
.SH "VOIR AUSSI"
.BR strpbrk (3),
.BR wcscspn (3),
.BR wcschr (3)
.SH TRADUCTION
Christophe Blaess, 2000-2003.
