.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single Unix specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.\" Traduction 29/08/2000 par Christophe Blaess (ccb@club-internet.fr)
.\" LDP 1.30
.\" MàJ 21/07/2003 LDP-1.56
.TH WCSSPN 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
wcsspn \- Balayer une chaîne de caractères larges en sautant un ensemble de caractères.
.SH SYNOPSIS
.nf
.B #include <wchar.h>
.sp
.BI "wcsspn (const wchar_t *" wcs ", const wchar_t *" accept );
.fi
.SH DESCRIPTION
La fonction \fBwcsspn\fP est l'équivalent pour les caractères larges de la fonction \fBstrspn\fP.
Elle calcule la longueur du plus long segment initial de \fIwcs\fP constitué uniquement de caractères larges
contenus dans \fIaccept\fP. En d'autres termes, elle recherche la première occurence d'un caractère large
non contenu dans \fIaccept\fP au sein de \fIwcs\fP.
.SH "VALEUR RENVOYÉE"
La fonction \fBwcsspn\fP renvoie le nombre de caractères larges dans le plus long segment initial de \fIwcs\fP constitué
uniquement de caractères se trouvant dans \fIaccept\fP. Autrement dit elle renvoie la position du premier caractère
large ne se trouvant pas dans \fIaccept\fP, ou \fIwcslen(wcs)\fP s'il n'y en a aucun.
.SH "CONFORMITÉ	"
ISO/ANSI C, UNIX98
.SH "VOIR AUSSI"
.BR strspn (3),
.BR wcscspn (3)
.SH TRADUCTION
Christophe Blaess, 2000-2003.
