.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single Unix specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\" MàJ 21/07/2003 LDP-1.56
.TH WMEMMOVE 3 "21 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
wmemmove \- Copier un tableau de caractères larges.
.SH SYNOPSIS
.nf
.B #include <wchar.h>
.sp
.BI "wchar_t *wmemmove (wchar_t *" dest ", const wchar_t *" src ", size_t " n );
.fi
.SH DESCRIPTION
La fonction \fBwmemmove\fP est l'équivalent pour les caractères larges de la
fonction \fBmemmove\fP. Elle copie \fIn\fP caractères larges depuis le tableau
pointé par \fIsrc\fP dans le tableau pointé par \fIdest\fP. Les tableaux
peuvent se recouvrir.
.PP
Le programmeur doit s'assurer qu'il y a suffisamment d'espace
pour au moins \fIn\fP caractères larges dans \fIdest\fP.
.SH "VALEUR RENVOYÉE"
\fBwmemmove\fP renvoie \fIdest\fP.
.SH "CONFORME A"
ISO/ANSI C, UNIX98
.SH "VOIR AUSSI"
.BR memmove (3),
.BR wmemcpy (3)
.SH TRADUCTION
.RI "Thierry Vignaud <" tvignaud@mandrakesoft.com ">, 2000"
