.\"  Copyright 2003 walter harms (walter.harms@informatik.uni-oldenburg.de)
.\"  Distributed under GPL
.\"  this is the 3rd type of interface for cryptographic routines
.\"  1. encrypt() expects a bitfield
.\"  2. cbc_crypt() byte values
.\"  3. xencrypt() a hexstring
.\"  to bad to be true :(
.\" Traduction Christophe Blaess <ccb@club-internet.fr>
.\" 30/07/2003 LDP-1.58
.TH XCRYPT 3 "30 juillet 2003" LDP "Manuel du programmeur Linux"
.SH NOM
xencrypt, xdecrypt, passwd2des \- Cryptage de mots de passe RFS.
.SH SYNOPSIS
.sp
.B "#include <rpc/des_crypt.h>"
.sp
.BR "void passwd2des (char " *passwd ", char *" key ");"
.sp
.BR "int xencrypt (char " *secret ", char *" passwd ");"
.sp
.BR "int xdecrypt (char " *secret ", char *" passwd ");"
.sp
.SH DESCRIPTION
La fonction
.B passwd2des()
prend une chaîne de caractère
.I passwd
d'une longueur quelconque et remplit une table
.I key
de longueur 8 octets. La table
.I key
est utilisable comme clé DES. Elle a le bit de parité mis à zéro dans chaque
octet. Les deux autres fonctions utilisent cette fonction pour
tranformer leur argument
.I passwd
en clé DES.
.LP
La fonction
.B xencrypt()
prend une chaîne de caractère Ascii
.I secret
données en hexadécimal,
.\" (over the alphabet 0123456789abcdefABCDEF),
qui doit avoir une longueur multiple de 16, la crypte en utilisant
la clé DES trouvé dérivée de
.I passwd
par
.BR passwd2des() ,
et renvoie le résultat dans
.I secret
comme une chaîne hexadécimale
.\" (over the alphabet 0123456789abcdef)
de même longueur.
.LP
La fonction
.B xdecrypt()
effectue la conversion inverse.
.SH "VALEUR RENVOYÉE"
Les fonctions
.B xencrypt()
et
.B xdecrypt()
renvoient 1 si elles réussissent et 0 en cas d'erreur.
.SH DISPONIBILITÉ
Ces routines sont présentes dans la libC 4.6.37 et ultérieures, et dans
GlibC 2.1 et ultérieures.
.SH BOGUES
Les prototypes sont absents des fichiers d'en-tête indiqués plus haut.
.SH "VOIR AUSSI"
.BR cbc_crypt (3)
.SH TRADUCTION
Christophe Blaess, 2003.
