.\" Copyright (c) 1993 Michael Haardt (u31b3hs@pool.informatik.rwth-aachen.de), Fri Apr  2 11:32:09 MET DST 1993
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139,
.\" USA.
.\"
.\" Modified Sat Jul 24 17:01:11 1993 by Rik Faith (faith@cs.unc.edu)
.\" Traduction 18/10/1996 par Christophe Blaess (ccb@club-internet.fr)
.\"
.\" Màj 06/06/2001 - LDP-man-pages-1.36
.\" LDP 1.47
.\" Màj 25/07/2003 LDP-1.56
.\" Màj 01/05/2006 LDP-1.67.1
.\"
.TH RAM 4 "21 novembre 1992" LDP "Manuel du programmeur Linux"
.SH NOM
ram \- Périphérique disque virtuel.
.SH DESCRIPTION
Le périphérique \fBram\fP
est un fichier bloc utilisé pour accéder de manière directe au
disque virtuel.
.LP
Il est typiquement créé ainsi\ :
.RS
.sp
mknod \-m 660 /dev/ram b 1 1
.br
chown root:disk /dev/ram
.sp
.RE
.SH FICHIERS
/dev/ram
.SH "VOIR AUSSI"
.BR mknod (1),
.BR chown (1),
.BR mount (8)
.SH TRADUCTION
.PP
Ce document est une traduction réalisée par Christophe Blaess
<http://www.blaess.fr/christophe/> le 18\ octobre\ 1996
et révisée le 2\ mai\ 2006.
.PP
L'équipe de traduction a fait le maximum pour réaliser une adaptation
française de qualité. La version anglaise la plus à jour de ce document est
toujours consultable via la commande\ : «\ \fBLANG=en\ man\ 4\ ram\fR\ ».
N'hésitez pas à signaler à l'auteur ou au traducteur, selon le cas, toute
erreur dans cette page de manuel.