'\" t
.\" Copyright 1999      Dimitri Papadopoulos (dpo@club-internet.fr)
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\" Traduction : Alain Portal
.\" 30/11/2004 LDP-1.58
.\" Màj 27/06/2005 LDP-1.60
.\"
.TH ISO_8859-7 7 "31 mai 1999" "Linux" "Manuel du programmeur Linux"
.nh

.SH NOM
iso_8859-7 \- la table de caractères ISO 8859-7 encodée en octal, décimal et
hexadécimal

.SH DESCRIPTION
La norme ISO 8859 inclut plusieurs extensions 8 bits au jeu de caractères
ASCII (également appelé ISO 646-IRV). L'ISO 8859-7 encode les caractères
utilisés en grec moderne.
.SS "Alphabets ISO 8859"
L'ensemble des alphabets ISO 8859 se compose de\ :
.P
.TS
l l.
ISO 8859-1	Langues d'Europe de l'Ouest (Latin-1)
ISO 8859-2	Langues d'Europe Centrale et d'Europe de l'Est (Latin-2)
ISO 8859-3	Langues d'Europe du Sud-Est et autres (Latin-3)
ISO 8859-4	Langues scandinave et balte (Latin-4)
ISO 8859-5	Latin/Cyrillique
ISO 8859-6	Latin/Arabe
ISO 8859-7	Latin/Grec
ISO 8859-8	Latin/Hébreu
ISO 8859-9	Latin-1 modifié pour le turc (Latin-5)
ISO 8859-10	Langues lappone/nordique/eskimaude (Latin-6)
ISO 8859-11	Latin/Thaï
ISO 8859-13	Langues de la ceinture baltique (Latin-7)
ISO 8859-14	Celte (Latin-8)
ISO 8859-15	Langues d'Europe de l'Ouest (Latin-9)
ISO 8859-16	Roumain (Latin-10)
.TE
.SS "Caractères ISO 8859-7"
Le tableau suivant affiche les caractères de l'ISO 8859-7 qui sont
imprimables et non disponibles dans la page de manuel
.BR ascii (7).
La quatrième colonne affichera correctement les glyphes seulement dans un
environnement configuré pour l'ISO 8859-7.

.TS
l l l c lp-1.
Oct	Déc	Hex	Carac	Description
_
240	160	A0	 	Espace insécable
241	161	A1	¡	Modificateur de lettre virgule renversée
242	162	A2	¢	Modificateur de lettre apostrophe
243	163	A3	£	Symbole monétaire livre
246	166	A6	Š	Barre verticale interrompue
247	167	A7	§	Symbole section
250	168	A8	š	Tréma
251	169	A9	©	Symbole copyright
253	171	AB	«	Guillemet français ouvrant
254	172	AC	¬	Symbole négation
255	173	AD	­	Trait d'union
257	175	AF	¯	Barre horizontale
260	176	B0	°	Symbole degré
261	177	B1	±	Symbole plus-moins
262	178	B2	²	Exposant 2
263	179	B3	³	Exposant 3
264	180	B4	Ž	Diacritique grec tonos
265	181	B5	µ	Diacritique grec tréma et tonos
266	182	B6	¶	Lettre capitale grecque ALPHA tonos
267	183	B7	·	Point à mi-hauteur
270	184	B8	ž	Lettre capitale grecque EPSILON tonos
271	185	B9	¹	Lettre capitale grecque ETA tonos
272	186	BA	º	Lettre capitale grecque IOTA tonos
273	187	BB	»	Guillemet français fermant
274	188	BC	Œ	Lettre capitale grecque OMICRON tonos
275	189	BD	œ	Fraction un demi
276	190	BE	Ÿ	Lettre capitale grecque UPSILON tonos
277	191	BF	¿	Lettre capitale grecque OMEGA tonos
300	192	C0	À	Lettre minuscule grecque IOTA tréma et tonos
301	193	C1	Á	Lettre capitale grecque ALPHA
302	194	C2	Â	Lettre capitale grecque BETA
303	195	C3	Ã	Lettre capitale grecque GAMMA
304	196	C4	Ä	Lettre capitale grecque DELTA
305	197	C5	Å	Lettre capitale grecque EPSILON
306	198	C6	Æ	Lettre capitale grecque ZETA
307	199	C7	Ç	Lettre capitale grecque ETA
310	200	C8	È	Lettre capitale grecque THETA
311	201	C9	É	Lettre capitale grecque IOTA
312	202	CA	Ê	Lettre capitale grecque KAPPA
313	203	CB	Ë	Lettre capitale grecque LAMDA
314	204	CC	Ì	Lettre capitale grecque MU
315	205	CD	Í	Lettre capitale grecque NU
316	206	CE	Î	Lettre capitale grecque XI
317	207	CF	Ï	Lettre capitale grecque OMICRON
320	208	D0	Ð	Lettre capitale grecque PI
321	209	D1	Ñ	Lettre capitale grecque RHO
323	211	D3	Ó	Lettre capitale grecque SIGMA
324	212	D4	Ô	Lettre capitale grecque TAU
325	213	D5	Õ	Lettre capitale grecque UPSILON
326	214	D6	Ö	Lettre capitale grecque PHI
327	215	D7	×	Lettre capitale grecque CHI
330	216	D8	Ø	Lettre capitale grecque PSI
331	217	D9	Ù	Lettre capitale grecque OMEGA
332	218	DA	Ú	Lettre capitale grecque IOTA tréma
333	219	DB	Û	Lettre capitale grecque UPSILON tréma
334	220	DC	Ü	Lettre minuscule grecque ALPHA tonos
335	221	DD	Ý	Lettre minuscule grecque EPSILON tonos
336	222	DE	Þ	Lettre minuscule grecque ETA tonos
337	223	DF	ß	Lettre minuscule grecque IOTA tonos
340	224	E0	à	Lettre minuscule grecque UPSILON tréma et tonos
341	225	E1	á	Lettre minuscule grecque ALPHA
342	226	E2	â	Lettre minuscule grecque BETA
343	227	E3	ã	Lettre minuscule grecque GAMMA
344	228	E4	ä	Lettre minuscule grecque DELTA
345	229	E5	å	Lettre minuscule grecque EPSILON
346	230	E6	æ	Lettre minuscule grecque ZETA
347	231	E7	ç	Lettre minuscule grecque ETA
350	232	E8	è	Lettre minuscule grecque THETA
351	233	E9	é	Lettre minuscule grecque IOTA
352	234	EA	ê	Lettre minuscule grecque KAPPA
353	235	EB	ë	Lettre minuscule grecque LAMDA
354	236	EC	ì	Lettre minuscule grecque MU
355	237	ED	í	Lettre minuscule grecque NU
356	238	EE	î	Lettre minuscule grecque XI
357	239	EF	ï	Lettre minuscule grecque OMICRON
360	240	F0	ð	Lettre minuscule grecque PI
361	241	F1	ñ	Lettre minuscule grecque RHO
362	242	F2	ò	Lettre minuscule grecque FINAL SIGMA
363	243	F3	ó	Lettre minuscule grecque SIGMA
364	244	F4	ô	Lettre minuscule grecque TAU
365	245	F5	õ	Lettre minuscule grecque UPSILON
366	246	F6	ö	Lettre minuscule grecque PHI
367	247	F7	÷	Lettre minuscule grecque CHI
370	248	F8	ø	Lettre minuscule grecque PSI
371	249	F9	ù	Lettre minuscule grecque OMEGA
372	250	FA	ú	Lettre minuscule grecque IOTA tréma
373	251	FB	û	Lettre minuscule grecque UPSILON tréma
374	252	FC	ü	Lettre minuscule grecque OMICRON tonos
375	253	FD	ý	Lettre minuscule grecque UPSILON tonos
376	254	FE	þ	Lettre minuscule grecque OMEGA tonos
.TE

.SH HISTORIQUE
ISO 8859-7 était précédemment connu sous le nom de ELOT-928 ou ECMA-118:1986.

.SH "VOIR AUSSI"
.BR ascii (7)

.SH TRADUCTION
.PP
Ce document est une traduction réalisée par Alain Portal
<aportal AT univ-montp2 DOT fr>, avec le concours de Vincent Ramos
<sivanataraja AT free DOT fr>, le 29 novembre 2004.
.PP
L'équipe de traduction a fait le maximum pour réaliser une adaptation
française de qualité. La version anglaise la plus à jour de ce document est
toujours consultable via la commande\ : «\ \fBLANG=en\ man\ 7\ iso_8859-7\fR\ ».
N'hésitez pas à signaler à l'auteur ou au traducteur, selon le cas, toute
erreur dans cette page de manuel.
