'\" t
.\" Copyright 2001      Alexey Mahotkin <alexm@hsys.msk.ru>
.\"
.\" Lots of text ripped from http://koi8.pp.ru/
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\" Traduction : Alain Portal
.\" 30/11/2004 LDP-1.58
.\" Màj 27/06/2005 LDP-1.60
.\"
.TH KOI8-R 7 "28 mai 2001" "Linux" "Manuel du programmeur Linux"
.nh

.SH NOM
koi8-r \- la table des caractères russes encodée en octal, décimal et
hexadécimal

.SH DESCRIPTION
KOI8-R est le jeu de caractères pour encoder les textes russes pour beaucoup
de systèmes d'exploitation de type Unix. KOI8-R est un successeur à KOI-8, une
norme de-facto pour le courrier électronique, les forums de discussions, la
navigation et autres services interactifs sur Internet, pour au moins tout le
territoire de l'ex-Union Soviétique.
.PP
KOI8-R est défini par la RFC1489 (Déclaration du jeu de caractères
cyrilliques).

.SH NOTE
KOI8-R a été conçu pour les textes utilisant le russe et l'anglais et pour
couvrir seulement les caractères cyrilliques russes, aussi, si vous avez
besoin des caractères cyrilliques ukrainiens, biélorusses, etc. essayez plutôt
ISO-IR-111 ou KOI8-U (jeu de caractères ukrainiens), ou KOI8-C (pour les
textes anciens russes), qui sont identiques à KOI8-R dans la zone des lettres
cyrilliques russes.
.PP
Un jeu de caractères cyrilliques plus complet est aussi défini par
l'ISO-8859-5.

.SS "Caractères KOI8-R"
Le tableau suivant affiche les caractères de KOI8-R qui sont
imprimables et non disponibles dans la page de manuel
.BR ascii (7).

.TS
l l l c lp-1.
Oct	Déc	Hex	Carac	Description
_
200	128	80		Trait horizontal
201	129	81		Trait vertical
202	130	82		Trait vers le bas et un vers la droite
203	131	83		Trait vers le bas et un vers la gauche
204	132	84		Trait vers le haut et un vers la droite
205	133	85		Trait vers le haut et un vers la gauche
206	134	86		Trait vertical et un vers la droite
207	135	87		Trait vertical et un vers la gauche
210	136	88		Trait vers le bas et un horizontal
211	137	89		Trait vers le haut et un horizontal
212	138	8A		Trait vertical et un horizontal
213	139	8B		Demi bloc supérieur
214	140	8C		Demi bloc inférieur
215	141	8D		Bloc entier
216	142	8E		Demi bloc gauche
217	143	8F		Demi bloc droit
220	144	90		Ombrage léger
221	145	91		Ombrage moyen
222	146	92		Ombrage sombre
223	147	93		Demi intégrale supérieure
224	148	94		Petit carré noir
225	149	95		Opérateur puce
226	150	96		Racine carrée
227	151	97		Environ égal à
230	152	98		Inférieur ou égal à
231	153	99		Supérieur ou égal à
232	154	9A		Espace insécable
233	155	9B		Demi intégrale inférieure
234	156	9C		Symbole degré
235	157	9D		Exposant 2
236	158	9E		Point à mi-hauteur
237	159	9F		Symbole division
240	160	A0	 	Double trait horizontal
241	161	A1	¡	Double trait vertical
242	162	A2	¢	Simple trait vers le bas et un double vers la droite
243	163	A3	£	Lettre minuscule cyrillique IO
244	164	A4	€	Double trait vers le bas et un simple vers la droite
245	165	A5	¥	Double trait vers le bas et un double vers la droite
246	166	A6	Š	Simple trait vers le bas et un double vers la gauche
247	167	A7	§	Double trait vers le bas et un simple vers la gauche
250	168	A8	š	Double trait vers le bas et un double vers la gauche
251	169	A9	©	Simple trait vers le haut et un double vers la droite
252	170	AA	ª	Double trait vers le haut et un simple vers la droite
253	171	AB	«	Double trait vers le haut et un double vers la droite
254	172	AC	¬	Simple trait vers le haut et un double vers la gauche
255	173	AD	­	Double trait vers le haut et un simple vers la gauche
256	174	AE	®	Double trait vers le haut et un double vers la gauche
257	175	AF	¯	Simple trait vertical et un double vers la droite
260	176	B0	°	Double trait vertical et un simple vers la droite
261	177	B1	±	Double trait vertical et un double vers la droite
262	178	B2	²	Simple trait vertical et un double vers la gauche
263	179	B3	³	Lettre majuscule cyrillique IO
264	180	B4	Ž	Double trait vertical et un simple vers la gauche
265	181	B5	µ	Double trait vertical et un double vers la gauche
266	182	B6	¶	Simple trait vers le bas et un double horizontal
267	183	B7	·	Double trait vers le bas et un simple horizontal
270	184	B8	ž	Double trait vers le bas et un double horizontal
271	185	B9	¹	Simple trait vers le haut et un double horizontal
272	186	BA	º	Double trait vers le haut et un simple horizontal
273	187	BB	»	Double trait vers le haut et un double horizontal
274	188	BC	Œ	Simple trait vertical et un double horizontal
275	189	BD	œ	Double trait vertical et un simple horizontal
276	190	BE	Ÿ	Double trait vertical et un double horizontal
277	191	BF	¿	Symbole copyright
300	192	C0	À	Lettre minuscule cyrillique IU
301	193	C1	Á	Lettre minuscule cyrillique A
302	194	C2	Â	Lettre minuscule cyrillique BE
303	195	C3	Ã	Lettre minuscule cyrillique TSE
304	196	C4	Ä	Lettre minuscule cyrillique DE
305	197	C5	Å	Lettre minuscule cyrillique IE
306	198	C6	Æ	Lettre minuscule cyrillique EF
307	199	C7	Ç	Lettre minuscule cyrillique GE
310	200	C8	È	Lettre minuscule cyrillique KHA
311	201	C9	É	Lettre minuscule cyrillique II
312	202	CA	Ê	Lettre minuscule cyrillique II bref
313	203	CB	Ë	Lettre minuscule cyrillique KA
314	204	CC	Ì	Lettre minuscule cyrillique EL
315	205	CD	Í	Lettre minuscule cyrillique EM
316	206	CE	Î	Lettre minuscule cyrillique EN
317	207	CF	Ï	Lettre minuscule cyrillique O
320	208	D0	Ð	Lettre minuscule cyrillique PE
321	209	D1	Ñ	Lettre minuscule cyrillique IA
322	210	D2	Ò	Lettre minuscule cyrillique ER
323	211	D3	Ó	Lettre minuscule cyrillique ES
324	212	D4	Ô	Lettre minuscule cyrillique TE
325	213	D5	Õ	Lettre minuscule cyrillique U
326	214	D6	Ö	Lettre minuscule cyrillique ZHE
327	215	D7	×	Lettre minuscule cyrillique VE
330	216	D8	Ø	Lettre minuscule cyrillique signe mou
331	217	D9	Ù	Lettre minuscule cyrillique YERI
332	218	DA	Ú	Lettre minuscule cyrillique ZE
333	219	DB	Û	Lettre minuscule cyrillique SHA
334	220	DC	Ü	Lettre minuscule cyrillique E inversée
335	221	DD	Ý	Lettre minuscule cyrillique SHCHA
336	222	DE	Þ	Lettre minuscule cyrillique CHE
337	223	DF	ß	Lettre minuscule cyrillique signe dur
340	224	E0	à	Lettre majuscule cyrillique IU
341	225	E1	á	Lettre majuscule cyrillique A
342	226	E2	â	Lettre majuscule cyrillique BE
343	227	E3	ã	Lettre majuscule cyrillique TSE
344	228	E4	ä	Lettre majuscule cyrillique DE
345	229	E5	å	Lettre majuscule cyrillique IE
346	230	E6	æ	Lettre majuscule cyrillique EF
347	231	E7	ç	Lettre majuscule cyrillique GE
350	232	E8	è	Lettre majuscule cyrillique KHA
351	233	E9	é	Lettre majuscule cyrillique II
352	234	EA	ê	Lettre majuscule cyrillique II bref
353	235	EB	ë	Lettre majuscule cyrillique KA
354	236	EC	ì	Lettre majuscule cyrillique EL
355	237	ED	í	Lettre majuscule cyrillique EM
356	238	EE	î	Lettre majuscule cyrillique EN
357	239	EF	ï	Lettre majuscule cyrillique O
360	240	F0	ð	Lettre majuscule cyrillique PE
361	241	F1	ñ	Lettre majuscule cyrillique IA
362	242	F2	ò	Lettre majuscule cyrillique ER
363	243	F3	ó	Lettre majuscule cyrillique ES
364	244	F4	ô	Lettre majuscule cyrillique TE
365	245	F5	õ	Lettre majuscule cyrillique U
366	246	F6	ö	Lettre majuscule cyrillique ZHE
367	247	F7	÷	Lettre majuscule cyrillique VE
370	248	F8	ø	Lettre majuscule cyrillique signe mou
371	249	F9	ù	Lettre majuscule cyrillique YERI
372	250	FA	ú	Lettre majuscule cyrillique ZE
373	251	FB	û	Lettre majuscule cyrillique SHA
374	252	FC	ü	Lettre majuscule cyrillique E inversée
375	253	FD	ý	Lettre majuscule cyrillique SHCHA
376	254	FE	þ	Lettre majuscule cyrillique CHE
377	255	FF	ÿ	Lettre majuscule cyrillique signe dur

.TE
.SH "VOIR AUSSI"
.BR ascii (7)
.BR iso-8859-7 (7)
(pas encore rédigé),
RFC1489,
http://koi8.pp.ru/

.SH TRADUCTION
.PP
Ce document est une traduction réalisée par Alain Portal
<aportal AT univ-montp2 DOT fr> le 29 novembre 2004.
.PP
L'équipe de traduction a fait le maximum pour réaliser une adaptation
française de qualité. La version anglaise la plus à jour de ce document est
toujours consultable via la commande\ : «\ \fBLANG=en\ man\ 7\ koi8-r\fR\ ».
N'hésitez pas à signaler à l'auteur ou au traducteur, selon le cas, toute
erreur dans cette page de manuel.
