.\" Copyright (c) 1995 Dirk Eddelbuettel (Dirk.Eddelbuettel@qed.econ.queensu.ca)
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139,
.\" USA.
.\" Traduction 28/08/2000 par Christophe Blaess (ccb@club-internet.fr)
.\" LDP 1.30
.\" Màj 06/06/2001 LDP-1.36
.\" Màj 25/07/2003 LDP-1.56
.\" Màj 04/07/2005 LDP-1.61
.\"
.TH ACCT 5 "1er novembre 2003" LDP "Manuel de l'administrateur Linux"
.SH NOM
acct \- Fichier de comptabilité d'exécution.
.SH SYNOPSIS
.B #include <sys/acct.h>
.SH DESCRIPTION
Si le noyau a été compilé avec l'option de comptabilité de processus activée,
l'appel système
.RS
acct("/quelque_part/fichier_comptabilité");
.RE
démarrera la comptabilité des processus. Chaque fois qu'un processus s'achève,
un enregistrement pour ce processus est ajouté au fichier de comptabilité.
La structure
.B "struct acct"
est décrite dans
.IR /usr/include/linux/acct.h .
.SH "VOIR AUSSI"
.BR sa (1),
.BR acct (2)
.SH TRADUCTION
Christophe Blaess, 2000-2003.

