.\" Copyright (c) 1994 Peter Tobias <tobias@server.et-inf.fho-emden.de>
.\" This file may be distributed under the GNU General Public License.
.\" MàJ 25/07/2003 LDP-1.56
.TH ISSUE.NET 5 "25 juillet 2003" LDP "Manuel de l administrateur Linux"
.SH NOM
issue.net \- fichier d'authentification pour les sessions telnet.
.SH DESCRIPTION 
Le fichier \fB/etc/issue.net\fP est un fichier texte qui contient un message ou une
identification du système à afficher avant l'invite de login d'une 
session telnet. Il peut contenir différentes séquences de caractères\ :
.BI '%'
 . Les séquences suivantes sont supportées par 
.BR telnetd " :"
.TP
.B %t
- affiche le tty utilisé
.TP
.B %h
- affiche le nom de la machine (FQDN)
.TP
.B %D
- affiche le nom du domaine NIS
.TP
.B %d
- affiche l'heure et la date
.TP
.B %s
- affiche le nom du système d'exploitation
.TP
.B %m
- montre le type de machine (CPU)
.TP
.B %r
- affiche la sous-version du système d'exploitation
.TP
.B %v
- affiche la version du système d'exploitation
.TP
.B %%
- affiche un caractère '%' unique.
.PP
.SH FICHIERS
/etc/issue.net
.SH "VOIR AUSSI"
.BR telnetd (8)
.SH TRADUCTION
.RI "Thierry Vignaud <" tvignaud@mandrakesoft.com ">, 1999"
