.\" Hey Emacs, this is -*- nroff -*-
.\"
.\" This file is part of locale(1) which displays the settings of the
.\" current locale.
.\" Copyright (C) 1994  Jochen Hein (Hein@Student.TU-Clausthal.de)
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\" Traduction 16/07/1997 par Christophe Blaess (ccb@club-internet.fr)
.\" Màj 25/07/2003 LDP-1.56
.\" Màj 04/07/2005 LDP-1.61
.\"
.TH LOCALE 5 "25 juillet 2003" LDP "Manuel de l'administrateur Linux"
.SH NOM
locale \- Description d'un fichier de définition locale.
.SH
DESCRIPTION
Un fichier de définition
.B locale
contient toutes les informations dont la commande
.B localedef(1)
a besoin pour créer la base de données locale binaire.

Le fichier de définition est constitué de sections, chacune d'entre-elles
décrivant en détail une catégorie d'information locale.
.SH SYNTAXE
Le fichier débute par un en-tête contenant les mots-clés suivants\ :
.TP
.I <escape_char>
suivi du caractère qui sera utilisé comme caractère d'échappement
dans le reste du fichier, pour préfixer les caractères ayant une
signification spéciale. Par défaut, il s'agit de la barre oblique inverse
.RB " «\ " \e "\ ».
.TP
.I <comment_char>
suivi d'un caractère qui servira à introduire des commentaires dans
le reste du fichier. Par défaut, il s'agit du dièse
.RB " «\ " # "\ ».

.PP
La définition de la localisation est divisée en plusieurs parties,
chacune d'elles représentant une catégorie de localisation.
Une partie peut être copiée directement depuis une autre localisation
existante, ou peut être définie entièrement. Si l'on désire copier
intégralement une catégorie, le seul mot-clé valide est
.B copy
suivi du nom de la localisation initiale.

.SS LC_CTYPE
La définition de la catégorie
.B LC_CTYPE
définissant la typographie locale commence avec la chaîne
.I LC_CTYPE
en première colonne.

Les mots-clés suivants sont autorisés\ :

.TP
.I upper
suivi d'une liste de lettres majuscules. Les lettres
.BR A
à
.BR Z
sont inclues automatiquement. Les caractères indiqués dans les
classes
.BR cntrl ,
.BR digit ,
.BR punct ,
ou
.B space
ne sont pas autorisés.

.TP
.I lower
suivi d'une liste de lettres minuscules. Les lettres
.B a
à
.B z
sont inclues automatiquement. Les caractères indiqués dans les
classes
.BR cntrl ,
.BR digit ,
.BR punct ,
ou
.B space
ne sont pas autorisés.

.TP
.I alpha
suivi d'une liste de lettres. Tous les caractères mentionnés
dans
.B upper
ou
.B lower
sont inclus automatiquement. Les caractères indiqués dans les
classes
.BR cntrl ,
.BR digit ,
.BR punct ,
ou
.B space
ne sont pas autorisés.

.TP
.I digit
suivi d'une liste de chiffres. Seuls les caractères
.B 0
à
.B 9
sont autorisés. Ils sont inclus automatiquement dans cette classe.

.TP
.I space
suivi d'une liste de caractères considérés comme une espace blanche.
Les caractères indiqués dans les classes
.BR upper ,
.BR lower ,
.BR alpha ,
.BR digit ,
.BR graph ,
ou
.B xdigit
ne sont pas autorisés.
Les caractères
.BR <space> " (espace), "
.BR <form-feed> " (saut de page), "
.BR <newline> " (saut de ligne), "
.BR <carriage-return> " (retour chariot), "
.BR <tab>,
et
.B <vertical-tab>
sont inclus automatiquement.

.TP
.I cntrl
suivi d'une liste de caractères de contrôle.
Les caractères mentionnés dans les classes
.BR upper ,
.BR lower ,
.BR alpha ,
.BR digit ,
.BR punct ,
.BR graph ,
.BR print ,
ou
.B xdigit
ne sont pas autorisés.

.TP
.I punct
suivi d'une liste de caractères de ponctuation.
Les caractères mentionnés dans les classes
.BR upper ,
.BR lower ,
.BR alpha ,
.BR digit ,
.BR cntrl ,
.BR xdigit ,
et le caractère
.B <space>
(espace) ne sont pas autorisés.

.TP
.I graph
suivi d'une liste de caractères affichables, sauf l'espace.
Les caractères mentionnés dans les classes
.BR upper ,
.BR lower ,
.BR alpha ,
.BR digit ,
.BR xdigit ,
.B upper, lower, alpha, digit, xdigit
et
.B punct
sont inclus automatiquement.
Les caractères mentionnés dans la classe
.B cntrl
ne sont pas autorisés.

.TP
.I print
suivi d'une liste de caractères affichables, y compris l'espace.
Les caractères mentionnés dans les classes
.BR upper ,
.BR lower ,
.BR alpha ,
.BR digit ,
.BR xdigit ,
.BR punct ,
et le caractère
.B <space>
sont inclus automatiquement.
Les caractères mentionnés dans la classe
.B cntrl
ne sont pas autorisés.

.TP
.I xdigit
suivi d'une liste de caractères représentant les chiffres hexadécimaux.
Les chiffres décimaux doivent être mentionnés, suivi d'un ou plusieurs
ensembles de six caractères, en ordre croissant.
Les caractères suivant sont inclus par défaut\ :
.B 0
à
.B 9,
.B a
à
.B f,
.B A
à
.B F.

.TP
.I blank
suivi d'une liste de caractères blancs.
L'espace
.B <space>
et la tabulation
.B <tab>
sont inclus automatiquement.

.TP
.I toupper
suivi d'une liste de correspondance entre majuscules et minuscules.
Chaque correspondance est représentée par une paire de lettres majuscule
et minuscule, séparées par une virgule
.B ,
et entourée de parenthèses.
Les correspondances sont séparées par des points-virgules.
.TP
.I tolower
suivi d'une liste de correspondance entre minuscules et majuscules.
Si le mot-cle \fItolower\fP est absent, la liste inverse de
\fItoupper\fP est utilisée.

.PP
La définition de la catégorie
.B LC_CTYPE
se termine avec la chaîne de caractères
.I END LC_CYTPE.

.SS LC_COLLATE

Ndt\ : Je n'ai pas compris cette catégorie. J'imagine, sans certitude,
qu'elle concerne les caractères superposés (par exemple\ :
un accent «\ mort\ » suivi de la lettre à accentuer), ou
collés (par exemple\ : «\ o\ » et «\ e\ » dans «\ oeil\ »).
Je laisse donc quelques phrases en anglais, de toute manière ce
paragraphe est bien insuffisant, je trouve...

The
.B LC_COLLATE
category defines the rules for collating characters.

À cause des limitations de la libc,
les options POSIX ne sont pas toutes implémentées.
La définition commence avec la chaîne
.B LC_COLLATE
en première colonne.

Les mots-clés suivants sont autorisés\ :

.TP
.I collating-element

.TP
.I collating-symbol

.PP
The order-definition starts with a line:
.TP
.I order_start
.PP
followed by a list of keywords out of
.B forward,
.B backward
or
.B position.
The order definition consists of lines that describe the order
and is terminated with the keyword
.TP
.IR order_end .
.PP

Pour plus de détails, regardez les sources dans
.B /usr/lib/nls/src
notamment les paragraphes
.B POSIX,
.B Example
et
.BR Example2 .

.PP
La définition
.B LC_COLLATE
se termine par la chaîne
.I END LC_COLLATE.

.SS LC_MONETARY
La définition commence par la chaîne
.B LC_MONETARY
en première colonne.

Les mots-clés suivants sont autorisés\ :

.TP
.I int_curr_symbol
suivi du code international de symbole monétaire. Il s'agit d'une
chaîne de 4 caractères composée du code défini dans le standard
ISO 4217 (trois caractères) suivie d'un séparateur.
.TP
.I currency_symbol
suivi du symbole monétaire local.
.TP
.I mon_decimal_point
suivi de la chaîne à utiliser comme délimiteur décimal
lors de la mise en forme de valeurs monétaires.
.TP
.I mon_thousands_sep
suivi de la chaîne à utiliser comme séparateur de groupes de chiffres
lors de la mise en forme de valeurs monétaires.
.TP
.I mon_grouping
suivi d'une chaîne décrivant la mise en forme numérique de
valeurs monétaires.
.TP
.I positive_sign
suivi de la chaîne à utiliser comme signe positif
lors de la mise en forme de valeurs monétaires.
.TP
.I negative_sign
suivi de la chaîne à utiliser comme indicateur négatif
lors de la mise en forme de valeurs monétaires.
.TP
.I int_frac_digits
suivi du nombre de décimales à afficher
lors de la mise en forme avec le symbole
.BR int_curr_symbol .
.TP
.I frac_digits
suivi du nombre de décimales à afficher
lors de la mise en forme avec le symbole
.BR currency_symbol .
.TP
.I p_cs_precedes
suivi d'un entier valant
.B 1
si les symboles monétaires
.I currency_symbol
ou
.I int_curr_symbol
doivent précéder la valeur numérique, et
.B 0
s'ils doivent suivre la valeur numérique.
.TP
.I p_sep_by_space
suivi d'un entier.
.RS
.TP
.B 0
signifie qu'aucune espace ne doit être insérée entre le symbole et
la valeur.
.TP
.B 1
signifie qu'une espace doit être insérée entre le symbole et
la valeur.
.TP
.B 2
signifie qu'une espace doit être inséré entre le symbole monétaire et le symbole de signe positif s'ils sont adjacents.
.RE
.TP
.I n_cs_precedes
.RS
.TP
.B 0
- le symbole suit la valeur
.TP
.B 1
- le symbole précède la valeur
.RE
.TP
.I n_sep_by_space
Un entier valant
.B 0
si aucune espace ne sépare les symboles
.I currency_symbol
ou
.I int_curr_symbol
de la valeur pour une quantité négative,
.B 1
si une espace sépare le symbole de la valeur, et
.B 2
si une espace sépare le symbole du signe s'ils sont adjacents.
.TP
.I p_sign_posn
.RS
.TP
.B 0
Des parenthèses encadrent la valeur et les symboles
.I currency_symbol
ou
.I int_curr_symbol.
.TP
.B 1
Le signe précède la valeur et les symboles
.I currency_symbol
ou
.I int_curr_symbol.
.TP
.B 2
Le signe suit la valeur et les symboles
.I currency_symbol
ou
.I int_curr_symbol.
.TP
.B 3
Le signe précède les symboles
.I currency_symbol
ou
.I int_curr_symbol.
.TP
.B 4
Le signe suit les symboles
.I currency_symbol
ou
.I int_curr_symbol.
.RE
.TP
.I n_sign_posn
.RS
.TP
.B 0
Des parenthèses encadrent la valeur et les symboles
.I currency_symbol
ou
.I int_curr_symbol.
.TP
.B 1
Le signe précède la valeur et les symboles
.I currency_symbol
ou
.I int_curr_symbol.
.TP
.B 2
Le signe suit la valeur et les symboles
.I currency_symbol
ou
.I int_curr_symbol.
.TP
.B 3
Le signe précède les symboles
.I currency_symbol
ou
.I int_curr_symbol.
.TP
.B 4
Le signe suit les symboles
.I currency_symbol
ou
.I int_curr_symbol.
.RE
.PP
La définition
.B LC_MONETARY
se termine par la chaîne
.IR END LC_MONETARY .

.SS LC_NUMERIC
La définition de cette catégorie commence par la chaîne
.B LC_NUMERIC
en première colonne.

Les mots-clés suivants sont autorisés\ :

.TP
.I decimal_point
suivi d'une chaîne indiquant le séparateur decimal
lors de la mise en forme d'une valeur numérique.
.TP
.I thousands_sep
suivi d'une chaîne indiquant le séparateur de groupes
lors de la mise en forme d'une valeur numérique.
.TP
.I grouping
suivi d'une chaîne décrivant la mise en forme
d'une valeur numérique.
.PP
La définition de la catégorie
.B LC_NUMERIC
se termine par la chaîne
.I END LC_NUMERIC.

.SS LC_TIME
La définition débute par la chaîne
.B LC_TIME
en première colonne.

Les mots-clés suivants sont autorisés\ :

.TP
.I abday
suivi d'une liste des noms de jours abrégés. La liste commence par
le Dimanche (Sunday).
.TP
.I day
suivi d'une liste des noms de jours. La liste commence par
le Dimanche (Sunday).
.TP
.I abmon
suivi d'une liste des noms de mois abrégés.
.TP
.I mon
suivi d'une liste des noms de mois.
.TP
.I am_pm
suivi de la représentation locale des chaînes
.B am
et
.BR pm .
.TP
.I d_t_fmt
Le format local de la date et de l'heure.
.TP
.I d_fmt
Le format local de la date.
.TP
.I t_fmt
Le format local pour l'heure.
.TP
.I t_fmt_ampm
Le format local pour l'heure sur un cadran de 12 heures.
.PP
La définition de la catégorie
.B LC_TIME
se termine par la chaîne
.IR END LC_TIME .

.SS LC_MESSAGES
La définition de cette catégorie commence par la chaîne
.B LC_MESSAGES
en première colonne.

Les mots-clés suivants sont reconnus\ :

.TP
.I yesexpr
suivi d'une expression rationnelle correspondant à une réponse affirmative.
.TP
.I noexpr
suivi d'une expression rationnelle correspondant à une réponse négative.

.PP
La définition de la catégorie
.B LC_MESSAGES
se termine par la chaîne
.I END LC_MESSAGES.

Se référer au standard POSIX.2 pour plus de détails.
.SH FICHIERS
.RS
.TP
/usr/lib/locale/
base de données des localisations installées.
.TP
/usr/lib/nls/charmap/*
tables de caractères.
.RS
.SH BOGUES
Cette page est incomplète.
.\".SH AUTEUR
.\"Jochen Hein (Hein@Student.TU-Clausthal.de)
.SH "CONFORMITÉ"
POSIX.2
.SH "VOIR AUSSI"
.BR setlocale (3),
.BR localeconv (3),
.BR charmap (5),
.BR locale (1),
.BR localedef (1)

.SH TRADUCTION
Christophe Blaess, 1996-2003.
