PACKAGE=coreutils

include ../Makefile.common

post-build:
	if [ -e french/man1/test.1 ]; then \
	  ln -sf test.1 french/man1/[.1; \
	fi;
	if [ -e french/man1/md5sum.1 ]; then \
	  ln -sf md5sum.1 french/man1/md5sum.textutils.1; \
	fi;
