.\" Copyright 1992, 1993 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.\" Traduction 29/08/2000 par Frédéric Delanoy (delanoy_f@yahoo.com)
.\" (util-linux v2.11m)
.\"
.\" MàJ 30/07/2003 util-linux-2.11y
.TH FDFORMAT 8 "30 juillet 2003" "util-linux" "Manuel de l utilisateur Linux"
.SH NOM
fdformat \- Effectuer un formatage de bas niveau sur une disquette.
.SH SYNOPSIS
.B fdformat
.B "[ \-n ]"
périphérique
.SH DESCRIPTION
.B fdformat
effectue un formatage de bas niveau sur une disquette.
.I périphérique
est habituellement l'une des valeurs suivantes (pour les périphériques
de type disquette, le numéro majeur vaut 2, et le numéro mineur n'est
montré que pour information)\ :
.sp
.nf
.RS
/dev/fd0d360  (mineur = 4)
/dev/fd0h1200 (mineur = 8)
/dev/fd0D360  (mineur = 12)
/dev/fd0H360  (mineur = 12)
/dev/fd0D720  (mineur = 16)
/dev/fd0H720  (mineur = 16)
/dev/fd0h360  (mineur = 20)
/dev/fd0h720  (mineur = 24)
/dev/fd0H1440 (mineur = 28)

/dev/fd1d360  (mineur = 5)
/dev/fd1h1200 (mineur = 9)
/dev/fd1D360  (mineur = 13)
/dev/fd1H360  (mineur = 13)
/dev/fd1D720  (mineur = 17)
/dev/fd1H720  (mineur = 17)
/dev/fd1h360  (mineur = 21)
/dev/fd1h720  (mineur = 25)
/dev/fd1H1440 (mineur = 29)
.RE
.fi

Les périphériques de disquettes génériques, à savoir /fd0 et /dev/fd1, ne
fonctionneront pas avec
.B fdformat
quand un format non standard est utilisé, ou si le format n'a pas été
autodétecté au préalable. Dans ce cas, utilisez
.BR setfdprm (8)
pour charger les paramètres du disque.

.SH OPTIONS
.TP
.B \-n
Aucune vérification. Cette option désactivera la vérification qui est
effectuée après le formatage.

.SH "VOIR AUSSI"
.BR fd (4),
.BR setfdprm (8),
.BR mkfs (8),
.BR emkfs (8)
.SH AUTEUR
Werner Almesberger (almesber@nessie.cs.id.ethz.ch)

.SH TRADUCTION
Frédéric Delanoy <\fIdelanoy_f at yahoo.com\fR>, 2000.
