.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.\" MàJ 30/07/2003 util-linux-2.11y
.TH IPCS 8 "30 juillet 2003" "util-linux" "Manuel de l utilisateur Linux"
.SH NOM
ipcs \- Fournit des informations sur l'usage des ressources IPC.
.SH SYNOPSIS
.B ipcs [ \-asmq ] [ \-tclup ]
.br
.BI "ipcs [ \-smq ] \-i " id
.br
.B ipcs \-h
.SH DESCRIPTION
.B ipcs
fournit des informations sur l'usage des ressources IPC pour lesquelles
le processus appelant a accès en lecture.

L'option
.B \-i
autorise la ressource spécifique
.I id
à être indiquée. Seules les informations sur cette ressource
.I id
seront imprimées.

Les ressources peuvent être indiquées comme suit :
.TP
.B \-m
zones de mémoires partagées
.TP
.B \-q
files de messages
.TP
.B \-s
tableaux de sémaphores
.TP
.B \-a
tous (option par défaut)
.PP
Le format de sortie peut être modifié ainsi:
.TP
.B \-t
heure
.TP
.B \-p
pid (Processus IDentification)
.TP
.B \-c
créateur
.TP
.B \-l
limites
.TP
.B \-u
résumé
.SH VOIR AUSSI
.BR ipcrm (8)
.SH AUTEUR
krishna balasubramanian (balasub@cis.ohio-state.edu)
.SH TRADUCTION
.RI "Thierry Vignaud <" tvignaud@mandrakesoft.com ">, 1999."
