.\" Rick Sladkey <jrs@world.std.com>
.\" In the public domain.
.\" Path modifications by faith@cs.unc.edu
.\" MàJ 25/07/2003 util-linux-2.11y
.TH SETSID 8 "25 juillet 2003" "Util-Linux" "Manuel de l'administrateur Linux"
.SH NOM
setsid \- Lancer un programme dans une nouvelle session.
.SH SYNOPSIS
.BI setsid " programme" " [ " "arg ..." " ]"
.SH DESCRIPTION
.B setsid
lance un programme dans une nouvelle session.
.SH "VOIR AUSSI"
.BR setsid (2)
.SH AUTEUR
Rick Sladkey <jrs@world.std.com>
.SH TRADUCTION
.RI "Thierry Vignaud <" tvignaud@mandrakesoft.com ">, 1999."
.br
Christophe Blaess, 2003.
