.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Traduction  10/10/1996 Christophe BLAESS (ccb@club-internet.fr)
.\" Màj 03/06/1997
.\" Màj 18/07/2003 LDP-1.56
.\" Màj 01/05/2006 LDP-1.67.1
.\"
.TH GETPID 2 "23 juillet 1993" LDP "Manuel du programmeur Linux"
.SH NOM
getpid, getppid \- Obtenir l'identifiant d'un processus.
.SH SYNOPSIS
.B #include <sys/types.h>
.br
.B #include <unistd.h>
.sp
.B pid_t getpid(void);
.br
.B pid_t getppid(void);
.SH DESCRIPTION
.B getpid
renvoie l'ID du processus actif. Ceci est souvent utilisé par des
routines qui créent des fichiers temporaires uniques.

.B getppid
renvoie le PID du processus parent de celui en cours. Ceci est
régulièrement utilise après un
.BR fork (2)
pour établir la communication entre les deux processus issus du
même programme.
.SH ERREURS
Ces fonctions réussissent toujours.
.SH "CONFORMITÉ"
POSIX, BSD 4.3, SVID
.SH "VOIR AUSSI"
.BR exec (3),
.BR fork (2),
.BR kill (2),
.BR mkstemp (3),
.BR tmpnam (3),
.BR tempnam (3),
.BR tmpfile (3)
.SH TRADUCTION
.PP
Ce document est une traduction réalisée par Christophe Blaess
<http://www.blaess.fr/christophe/> le 10\ octobre\ 1996
et révisée le 2\ mai\ 2006.
.PP
L'équipe de traduction a fait le maximum pour réaliser une adaptation
française de qualité. La version anglaise la plus à jour de ce document est
toujours consultable via la commande\ : «\ \fBLANG=en\ man\ 2\ getpid\fR\ ».
N'hésitez pas à signaler à l'auteur ou au traducteur, selon le cas, toute
erreur dans cette page de manuel.
