.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Traduction  10/10/1996 Christophe BLAESS (ccb@club-internet.fr)
.\" Màj 09/04/1999 LDP-1.22
.\" Màj 18/07/2003 LDP-1.56
.\" Màj 01/05/2006 LDP-1.67.1
.\"
.TH GETUID 2 "23 juillet 1993" LDP "Manuel du programmeur Linux"
.SH NOM
getuid, geteuid \- Obtenir l'identifiant de l'utilisateur.
.SH SYNOPSIS
.B #include <unistd.h>
.br
.B #include <sys/types.h>
.sp
.B uid_t getuid(void);
.br
.B uid_t geteuid(void);
.SH DESCRIPTION
.B getuid
retourne l'UID réel du processus en cours.

.B geteuid
retourne l'UID effectif du processus en cours.

L'UID réel correspond à celui du processus appelant, l'UID effectif dépend
de l'état du bit Set\-UID du fichier exécuté.
.SH ERREURS
Ces fonctions réussissent toujours.
.SH "CONFORMITÉ"
POSIX, BSD 4.3
.SH "VOIR AUSSI"
.BR setreuid (2),
.BR setuid (2)
.SH TRADUCTION
.PP
Ce document est une traduction réalisée par Christophe Blaess
<http://www.blaess.fr/christophe/> le 10\ octobre\ 1996
et révisée le 2\ mai\ 2006.
.PP
L'équipe de traduction a fait le maximum pour réaliser une adaptation
française de qualité. La version anglaise la plus à jour de ce document est
toujours consultable via la commande\ : «\ \fBLANG=en\ man\ 2\ getuid\fR\ ».
N'hésitez pas à signaler à l'auteur ou au traducteur, selon le cas, toute
erreur dans cette page de manuel.
