.\" Traduction 09/01/1997 par Christophe Blaess (ccb@club-internet.fr)
.\" MàJ 30/07/2003 coreutils-4.5.3
.TH CKSUM 1 "30 juillet 2003" coreutils "Manuel de l utilisateur Linux"
.SH NOM
cksum \- Fournir le nombre d'octets d'un fichier ainsi qu'une somme de contrôle.
.SH SYNOPSIS
.B cksum
[\-\-help] [\-\-version] [fichier...]
.SH DESCRIPTION
Cette page de manuel documente la version GNU de
.B cksum
([NDT] : \fBcksum\fP = Check Sum - Somme de contrôle).

.B cksum
calcule une somme de contrôle (CRC cyclic redundancy check) pour chaque
fichier mentionné, ou pour l'entrée standard, si aucun nom de fichier n'est
fourni, ou si le nom `-' est indiqué.

Il affiche la somme CRC, le nombre d'octets et le nom de chaque fichier (sauf
s'il s'agit de l'entrée standard).
.PP
.B cksum
est généralement utilisé pour s'assurer de l'intégrité d'un fichier
transféré par un support non fiable (comme les news), ceci en comparant
le résultat de 
.B cksum
sur les fichiers reçus avec le résultat de
.B cksum
sur les fichiers originaux.

L'algorithme CRC est indiqué dans les standards POSIX.2. Il n'est pas
compatible avec les programmes
.B sum
de BSD ou SYSV, il est plus robuste.
.TP
.I "\-\-help"
Afficher un message d'aide sur la sortie standard et terminer normalement.
.TP
.I "\-\-version"
Afficher un numéro de version sur la sortie standard et terminer normalement.

.SH TRADUCTION
Christophe Blaess, 1996-2003.
