.\" Traduction 09/01/1997 par Christophe Blaess (ccb@club-internet.fr)
.\"
.\" MàJ 30/07/2003 coreutils-4.5.3
.TH DIRNAME 1 "30 juillet 2003" coreutils "Manuel de l utilisateur Linux"
.SH NOM
dirname \- Ne conserver que la partie répertoire d'un chemin d'accès.
.SH SYNOPSIS
.B dirname
nom_de_fichier
.br
.B dirname
{\-\-help,\-\-version}
.SH DESCRIPTION
Cette page de manuel documente la version GNU de
.BR dirname .

.B dirname
élimine le dernier composant délimité par un slash du
.IR nom_de_fichier .

Si le
.I nom_de_fichier
n'a qu'un seul composant,
.B dirname
affiche `.' (ce qui signifie `répertoire en cours').
.SS OPTIONS
.TP
.I "\-\-help"
Afficher un message d'aide sur la sortie standard et terminer normalement.
.TP
.I "\-\-version"
Afficher un numéro de version sur la sortie standard et terminer normalement.

.SH TRADUCTION
Christophe Blaess, 1997-2003.
