.\" Traduction 23/12/1996 par Christophe Blaess (ccb@club-internet.fr)
.\"
.\" MàJ 30/07/2003 coreutils-4.5.3
.TH FALSE 1 "30 juillet 2003" coreutils "Manuel de l utilisateur Linux"
.SH NOM
false \- Échouer en ne faisant rien.
.SH SYNOPSIS
.B false
.br
.B false
{\-\-help,\-\-version}
.SH DESCRIPTION
Cette page de manuel décrit la version GNU de
.B false
(et probablement toutes les autres versions aussi).

.B false
ne fait rien, mais renvoie un code de retour valant 1, signifiant ``échec''.

Il peut être utilisé pour prendre la place d'une commande devant échouer
dans un script shell (pour la mise au point par exemple).
.SS OPTIONS
Quand la version GNU de
.B false
est invoquée avec un unique argument, les options suivantes sont reconnues :
.TP
.I "\-\-help"
Afficher un message d'aide sur la sortie standard et se terminer normalement.
.TP
.I "\-\-version"
Afficher un numéro de version sur la sortie standard et se terminer normalement.

.SH TRADUCTION
Christophe Blaess, 1996-2003.
