.\"
.\" Traduction 08/06/1997 par Christophe Blaess (ccb@club-internet.fr)
.\"
.\" MàJ 30/07/2003 coreutils-4.5.3
.TH HOSTID 1 "30 juillet 2003" coreutils "Manuel de l utilisateur Linux"
.SH NOM
hostid \- Configurer ou afficher l'identificateur d'hôte.
.SH SYNOPSYS
.B hostid
[\-v] [\|\fIid-decimal\fR\|]
.SH DESCRIPTION
La commande
.B hostid
affiche l'identificateur de l'hôte en hexadécimal. L'affichage est
également fourni en décimal (entre parenthèses) si l'option \-v
est demandée.

Cette valeur numérique est censée être unique pour chaque hôte, et
est normalement fixée pour correspondre à l'adresse Internet de l'hôte.

Seul le Super-User peut fixer l'identificateur en fournissant un argument.
Cette valeur est enregistrée dans le fichier /etc/hostid une fois pour
toutes.

.SH AUTEUR
Mitch DSouza - (m.dsouza@mrc-apu.cam.ac.uk)

.SH "VOIR AUSSI"
.BR gethostid (2),
.BR sethostid (2).

.SH TRADUCTION
Christophe Blaess, 1997-2003.
