.\" Copyright 1995-2000 David Engel (david@ods.com)
.\" Copyright 1995 Rickard E. Faith (faith@cs.unc.edu)
.\" Copyright 2000 Ben Collins (bcollins@debian.org)
.\"    Redone for GLibc 2.2
.\" Copyright 2000 Jakub Jelinek (jakub@redhat.com)
.\"    Corrected.
.\" Most of this was copied from the README file.
.\" Do not restrict distribution.
.\" May be distributed under the GNU General Public License
.\" Traduction Christophe Blaess <ccb@club-internet.fr>
.\" Màj 25/07/2003 LDP-1.56
.\" Màj 04/07/2005 LDP-1.61
.\"
.TH LDD 1 "21 juillet 2003" LDP "Manuel de l'utilisateur Linux"
.SH NOM
ldd \- Affiche les bibliothèques partagées nécessaires.
.SH SYNOPSIS
.B ldd
.RB [OPTION]...
FICHIER...
.SH DESCRIPTION
.B ldd
Affiche la liste des bibliothèques partagées nécessaires pour chaque
programme ou bibliothèque passés sur la ligne de commande.
.SH OPTIONS
.TP
.B \-V\ \-\-version
Afficher le numéro de version de
.BR ldd .
.TP
.B \-v\ \-\-verbose
Afficher toutes les informations, y compris les versions des symboles.
.TP
.B \-d\ \-\-data\-relocs
Réaliser les déplacements et indiquer les objets manquants (ELF seulement).
.TP
.B \-r\ \-\-function\-relocs
Réaliser les déplacements pour les objets donnés et les fonctions, et
indiquer les objets ou fonctions manquants (ELF seulement).
.TP
.B \-\-help
Aide.
.SH NOTES
La version standard de
.B ldd
est livrée avec la GlibC2. La LibC5 fournissait une ancienne version,
toujours présente sur certains systèmes. Les options longues ne sont pas
supportées par la version de la LibC5. En revanche, celle de la GlibC2 ne
supporte pas
.B \-V
et a seulement l'équivalent
.BR \-\-version .
.LP
La version LibC5 utilise le nom de la bibliothèque donnée sur la ligne de
commande tel quel s'il contient un «\ /\ »\ ; sinon elle cherche la
bibliothèque aux emplacements standards. Pour l'utiliser sur une
bibliothèque dans le répertoire courant, préfixez son nom avec «\ ./\ ».
.SH BOGUES
.B ldd
ne fonctionne pas avec les bibliothèques partagées a.out.
.PP
.B ldd
ne fonctionne pas avec certains programmes a.out très anciens qui ont été
compilés avant que le support de
.B ldd
ne soit ajouté dans le compilateur.
Si vous utilisez
.B ldd
sur l'un de ces programmes, il sera lancé avec
\fIargc\fP = 0 et les résultats seront imprévisibles.
.\" .SH AUTHOR
.\" David Engel.
.\" Roland McGrath and Ulrich Drepper.
.SH "VOIR AUSSI"
.BR ldconfig (8),
.BR ld.so (8)
.SH TRADUCTION
Christophe Blaess, 2003.
