.\" Traduction 23/12/1996 par Christophe Blaess (ccb@club-internet.fr)
.\"
.\" MàJ 30/07/2003 coreutils-4.5.3
.TH LOGNAME 1 "30 juillet 2003" coreutils "Manuel de l utilisateur Linux"
.SH NOM
logname \- Afficher le nom de connexion de l'utilisateur.
.SH SYNOPSIS
.B logname [\-\-help] [\-\-version]
.SH DESCRIPTION
Cette page de manuel décrit la version GNU de
.BR logname .

.B logname
affiche le nom de l'utilisateur l'ayant invoqué, comme on le trouve dans
le fichier /etc/utmp, puis se termine avec un code de retour 0.

S'il n'y a pas d'enregistrement /etc/utmp pour le processus appelant,
.B logname
affiche un message d'erreur et se termine avec le code de retour 1.
.SS OPTIONS
.TP
.I "\-\-help"
Afficher un message d'aide sur la sortie standard et se terminer normalement.
.TP
.I "\-\-version"
Afficher un numéro de version sur la sortie standard et se terminer normalement.

.SH TRADUCTION
Christophe Blaess, 1997-2003.
