.\" Traduction 09/01/1997 par Christophe Blaess (ccb@club-internet.fr)
.\"
.\" MàJ 30/07/2003 coreutils-4.5.3
.TH PRINTF 1 "30 juillet 2003" coreutils "Manuel de l utilisateur Linux"
.SH NOM
printf \- Mettre en forme et afficher des données.
.SH SYNOPSIS
.B printf
format [argument...]
.br
.B printf
{\-\-help,\-\-version}
.SH DESCRIPTION
Cette page de manuel documente la version GNU de
.BR printf .

.B printf
affiche la chaîne de caractères
.IR format ,
en interprétant les directives `%' et les séquences d'échappement `\e'
de la même manière que la fonction C \fBprintf\fP(3).

L'argument
.I format
est ré-utilisé autant de fois qu'il le faut pour interpréter tous les
arguments fournis.
.P
.B printf
interprète `\e0ooo' comme un nombre octal (`ooo' s'étendant sur 0 à 3 chiffres)
indiquant le caractère à imprimer, et `\exhhh' comme un nombre hexadécimal 
(`hhh' s'étendant sur 1 à 3 chiffres) indiquant également le caractère à
afficher.

Il existe une séquence d'échappement supplémentaire `\ec', qui
permet d'arrêter la sortie de
.BR printf ,
et une directive supplémentaire `%b', qui affiche la chaîne de caractères
en argument en interprétant les séquences d'échappement `\e' qu'elle
contient de la même manière que pour la chaîne
.IR format .
.SS OPTIONS
Quand la version GNU de
.B printf
est invoquée avec un seul argument, les options suivantes sont reconnues :
.TP
.I "\-\-help"
Afficher un message d'aide sur la sortie standard et se terminer normalement.
.TP
.I "\-\-version"
Afficher un numéro de version sur la sortie standard et se terminer normalement.

.SH TRADUCTION
Christophe Blaess, 1997-2003.
