.\" Traduction 09/01/1997 par Christophe Blaess (ccb@club-internet.fr)
.\"
.\" MàJ 30/07/2003 coreutils-4.5.3
.TH PRINTENV 1 "30 juillet 2003" coreutils "Manuel de l utilisateur Linux"
.SH NOM
printenv \- Afficher tout ou partie de l'environnement.
.SH SYNOPSIS
.B printenv
[\-\-help] [\-\-version] [variable...]
.SH DESCRIPTION
Cette page de manuel documente la version GNU de
.BR printenv .

Si aucun argument n'est fourni,
.B printenv
affiche l'environnement complet. 

Si un ou plusieurs noms de variables 
sont indiqués, il affichera la valeur de celles qui sont effectivement
remplies, et rien pour les autres.
.PP
Le code de retour vaut :
.nf
0 si toutes les variables indiquées ont été trouvées.
1 si au moins une variable indiquée n'a pas été trouvée.
2 si une erreur d'écriture s'est produite.
.SS OPTIONS
.TP
.I "\-\-help"
Afficher un message d'aide sur la sortie standard et se terminer normalement.
.TP
.I "\-\-version"
Afficher un numéro de version sur la sortie standard et se terminer normalement.

.SH TRADUCTION
Christophe Blaess, 1997-2003.
