.\" Traduction 02/01/1997 par Christophe Blaess (ccb@club-internet.fr)
.\"
.\" MàJ 30/07/2003 coreutils-4.5.3
.TH PWD 1 "30 juillet 2003" coreutils "Manuel de l utilisateur Linux"
.SH NOM
pwd \- Afficher le nom du répertoire de travail en cours.
.SH SYNOPSIS
.B pwd
.br
.B pwd
{\-\-help,\-\-version}
.SH DESCRIPTION
Cette page de manuel documente la version GNU de
.BR pwd
([NDT] \fBpwd\fP = Print Working Directory).

.B pwd
affiche le nom complet du répertoire en cours.

Ceci signifie que tous les composants du chemin affiché seront de
vrais répertoires, aucun lien symbolique ne sera présent.
.PP
Remarquez que la plupart des shells Unix disposent d'une commande
.B pwd
intégrée ayant les mêmes fonctionnalités. Ainsi la simple évocation de
.B pwd
exécutera généralement la version intégrée, et non pas celle documentée
ici.
.SS OPTIONS
.TP
.I "\-\-help"
Afficher un message d'aide sur la sortie standard et se terminer normalement.
.TP
.I "\-\-version"
Afficher un numéro de version sur la sortie standard et se terminer normalement.

.SH TRADUCTION
Christophe Blaess, 1997-2003.
