.\" Traduction 14/01/1997 par Christophe Blaess (ccb@club-internet.fr)
.\"
.\" MàJ 30/07/2003 coreutils-4.5.3
.TH TAC 1 "30 juillet 2003" coreutils "Manuel de l utilisateur Linux"
.SH NOM
tac \- Concaténer et afficher des fichiers à l'envers.
.SH SYNOPSIS
.B tac
[\-br] [\-s chaîne] [\-\-before] [\-\-regex] [\-\-separator=chaîne]
[\-\-help] [\-\-version] [fichier...]
.SH DESCRIPTION
Cette page de manuel documente la version GNU de
.B tac
([NDT] : Comme son nom l'indique, \fBtac\fP est l'inverse de \fBcat\fP).

.B tac
copie les fichiers indiqués sur la sortie standard en inversant l'ordre
des enregistrements. 

Si aucun fichier n'est fourni, ou si le nom `\-' est
mentionné, la lecture se fera depuis l'entrée standard.

Les enregistrements sont séparés par une chaîne de caractères, ou par
un saut de ligne si aucune chaîne n'est indiquée.

Par défaut, la chaîne séparatrice est attachée à la fin de l'enregistrement
qui la précède.
.SS OPTIONS
.TP
.I "\-b, \-\-before"
La chaîne séparatrice est attachée au début de l'enregistrement
qui la suit.
.TP
.I "\-r, \-\-regex"
Le séparateur est une expression rationnelle.
.TP
.I "\-s chaîne, \-\-separator=chaîne"
Utiliser
.I chaîne
comme séparateur d'enregistrements.
.TP
.I "\-\-help"
Afficher un message d'aide sur la sortie standard et se terminer normalement.
.TP
.I "\-\-version"
Afficher un numéro de version sur la sortie standard et se terminer normalement.

.SH TRADUCTION
Christophe Blaess, 1997-2003.
