.\" MàJ 30/07/2003 tar-1.13.25
.TH TAR 1 "30 juillet 2003" tar "Manuel de l'utilisateur Linux"
.SH NOM
tar \- la version GNU de l'utilitaire tar de gestion d'archives.
.SH SYNOPSIS
.B tar
[
.B \-
]
.B A --catenate --concatenate \||\| c --create \||\| d --diff --compare \||\| r --append \||\| t --list \||\| u --update \||\| x -extract --get
[
.B --atime-preserve
]
[
.B -b, --block-size N
]
[
.B -B, --read-full-blocks
]
[
.B -C, --directory RÉP
]
[
.B --checkpoint	
]
[
.B -f, --file [NOM_HÔTE:]F
]
[
.B --force-local	
]
[
.B -F, --info-script F --new-volume-script F
]
[
.B -G, --incremental
]
[
.B -g, --listed-incremental F
]
[
.B -h, --dereference
]
[
.B -i, --ignore-zeros
]
[
.B -j, -I, --bzip
]
[
.B --ignore-failed-read
]
[
.B -k, --keep-old-files
]
[
.B -K, --starting-file F
]
[
.B -l, --one-file-system
]
[
.B -L, --tape-length N
]
[
.B -m, --modification-time
]
[
.B -M, --multi-volume
]
[
.B -N, --after-date DATE, --newer DATE
]
[
.B -o, --old-archive, --portability
]
[
.B -O, --to-stdout
]
[
.B -p, --same-permissions, --preserve-permissions
]
[
.B -P, --absolute-paths
]
[
.B --preserve	
]
[
.B -R, --record-number
]
[
.B --remove-files
]
[
.B -s, --same-order, --preserve-order
]
[
.B --same-owner
]
[
.B -S, --sparse
]
[
.B -T, --files-from F
]
[
.B --null	
]
[
.B --totals	
]
[
.B -v, --verbose
]
[
.B -V, --label NOM
]
[
.B --version	
]
[
.B -w, --interactive, --confirmation
]
[
.B -W, --verify	
]
[
.B --exclude FICHIER
]
[
.B -X, --exclude-from FICHIER
]
[
.B -Z, --compress, --uncompress
]
[
.B -z, --gzip, --ungzip	
]
[
.B --use-compress-program PROG
]
[
.B --block-compress
]
[
.B -[0-7][lmh]	
]
.TP
.I nomfichier1 [ nomfichier2, ... nomfichierN ] 
.TP
.I répertoire1 [ répertoire2, ... répertoireN ]
.SH DESCRIPTION
.LP
Voici la page de manuel de la version GNU de
.BR tar ,
un programme de gestion d'archive utilisé pour créer et restaurer des
fichiers à partir d'une archive connue sous le nom 
.IR tarfile.
Un fichier 
.IR tarfile
peut être sur un lecteur de bande, cependant il est possible de produire
un fichier
.IR tarfile
comme un fichier normal.
Le première argument de  
.B tar
doit être obligatoirement une de ces lettres\ :
.BR Acdrtux ,
suivie par n'importe quelles fonctions optionnelles.
Les arguments finaux de
.B tar
sont les noms des fichiers ou des répertoires qui doivent être archivés.
L'utilisation d'un nom de répertoire implique toujours que les
sous-répertoires seront inclus dans l'archive.
.SH "OPTIONS PRINCIPALES"
.TP
Il faut obligatoirement utiliser l'une des options suivantes\ :
.TP
.B -A, --catenate, --concatenate
ajouter des fichiers à une archive.
.TP
.B -c, --create	
créer une nouvelle archive.
.TP
.B -d, --diff, --compare
trouver les différence entre une archive et les fichiers indiqués.
.TP
.B --delete		
supprimer des fichiers d'une archive (à ne pas utiliser avec les lecteurs de
bandes\ !).
.TP
.B -r, --append		
ajouter des fichiers à la fin d'une archive.
.TP
.B -t, --list		
liste le contenu d'une archive.
.TP
.B -u, --update		
ajoute seulement les fichiers qui sont plus récents que ceux de l'archive.
.TP
.B -x, --extract, --get		
restaure les fichiers contenus dans une archive.
.SH "AUTRES OPTIONS"
.TP
.B --atime-preserve	
ne modifie pas les dates d'accès des fichiers de l'archive.
.TP
.B -b, --block-size N
impose des blocs de N*512 octets (par défaut N=20).
.TP
.B -B, --read-full-blocks	
reforme des blocs valides (pour lire les tubes 4.2BSD).
.TP 
.B -C, --directory RÉP
va dans le répertoire RÉP.
.TP 
.B --checkpoint		
affiche les noms des répertoires durant la lecture de l'archive.
.TP
.B -f, --file [NOM_HÔTE:]F	
utilise le fichier archive F ou le périphérique F (par défaut /dev/rmt0).
.TP
.B --force-local		
le fichier archive est local même si son nom contient un deux-points.
.TP 
.B -F, --info-script F --new-volume-script F 
lance un script à la fin de chaque bande (implique -M).
.TP
.B -G, --incremental	
crée/liste/restaure les anciens formats GNU de sauvegarde incrémentale.
.TP
.B -g, --listed-incremental F 
crée/liste/restaure les nouveaux formats GNU de sauvegarde incrémentale.
.TP 
.B -h, --dereference	
n'archive pas les liens symboliques, archive les fichiers vers lesquels ils pointent.
.TP
.B -i, --ignore-zeros	
ignore, dans l'archive, les blocs de zéros, qui correspondent normalement à EOF.
.TP
.TP
.B -j, -I, --bzip
filtrer l'archive via bzip2. Note\ : l'option -I est très déconseillée et pourra
avoir une autre signification plus tard.
.B --ignore-failed-read	
n'abandonne pas l'opération si un fichier est illisible.
.TP
.B -k, --keep-old-files	
conserve les fichiers existants\ ; ne les remplace pas par les fichiers
présents dans l'archive.
.TP
.B -K, --starting-file F	
commence par le fichier F dans l'archive.
.TP
.B -l, --one-file-system	
reste dans le système de fichiers local quand l'archive est créée.
.TP
.B -L, --tape-length N	
change la cassette (ou disquette, le support) après avoir écrit N*1024
octets.
.TP
.B -m, --modification-time	
ne restaure pas la date de modification du fichier. 
.TP
.B -M, --multi-volume
crée/liste/restaure les archives multivolumes.
.TP
.B -N, --after-date DATE, --newer DATE	
enregistre seulement les fichiers plus récents que DATE.
.TP
.B -o, --old-archive, --portability	
écrit une archive au format V7, plutôt qu'au format ANSI.
.TP
.B -O, --to-stdout		
restaure les fichiers vers la sortie standard.
.TP
.B -p, --same-permissions, --preserve-permissions 
restaure toutes les informations de protection.
.TP
.B -P, --absolute-paths	
n'enlève pas les '/' au début des noms des fichiers.
.TP
.B --preserve		
comme -p -s
.TP
.B -R, --record-number	
accompagne chaque message du numéro d'enregistrement au sein de l'archive.
.TP 
.B --remove-files		
efface les fichiers après les avoir ajoutés à l'archive.
.TP
.B -s, --same-order, --preserve-order	
la liste des fichiers à restaurer est triée dans l'ordre d'archivage.
.TP
.B --same-owner		
conserve les appartenances des fichiers restaurés.
.TP
.B -S, --sparse		
traite efficacement les fichiers à trous.
.TP 
.B -T, --files-from F
obtient la liste des fichiers à extraire ou à archiver depuis le fichier F.
.TP
.B --null			
lit les noms se terminant par des caractères nuls. Désactive l'option -C.
.TP
.B --totals		
affiche la taille totale de l'archive créée avec --create
.TP
.B -v, --verbose		
affiche la liste des fichiers traités.
.TP
.B -V, --label NOM	
crée une archive avec le nom de volume NOM.
.TP 
.B --version		
affiche la version de tar.
.TP
.B -w, --interactive, --confirmation	
demande une confirmation pour chaque action.
.TP
.B -W, --verify		
tente de vérifier l'archive après l'avoir produite.
.TP
.B --exclude FICHIER
exclut le fichier FICHIER du traitement.
.TP
.B -X, --exclude-from FICHIER
exclut du traitement les fichiers dont les noms sont contenus dans FICHIER.
.TP
.B -Z, --compress, --uncompress      	
compacte l'archive avec \fBcompress\FP.
.TP 
.B -z, --gzip, --ungzip		
compacte l'archive avec \fBgzip\fP.
.TP
.B --use-compress-program PROG
compacte l'archive en utilisant le programme PROG (qui doit accepter la option -d pour le décompactage).
.SH TRADUCTION
Jérome Signouret, 2000.
.br
Christophe Blaess 2003.
.SH RELECTURE
Gérard Delafond
