.\" Traduction 08/01/1997 par Christophe Blaess (ccb@club-internet.fr)
.\"
.\" MàJ 30/07/2003 coreutils-4.5.3
.TH TEE 1 "30 juillet 2003" coreutils "Manuel de l utilisateur Linux"
.SH NOM
tee \- Copier l'entrée standard sur la sortie standard et dans un fichier.
.SH SYNOPSIS
.B tee
[\-ai] [\-\-append] [\-\-ignore-interrupts] [\-\-help] [\-\-version] [fichier...]
.SH DESCRIPTION
Cette page de manuel documente la version GNU de
.BR tee .

La commande
.B tee
copie l'entrée standard sur la sortie standard, et dans tous les fichiers
fournis en argument.
.P
Si un fichier n'existe pas, il est créé. Si le fichier existe déjà, il est
écrasé, à moins que l'option
.I \-a
soit précisée.
.SS OPTIONS
.TP
.I "\-a, \-\-append"
Ajouter l'entrée standard aux fichiers indiqués plutôt que de les écraser.
.TP
.I "\-\-help"
Afficher un message d'aide sur la sortie standard et se terminer normalement.
.TP
.I "\-i, \-\-ignore-interrupts"
Ignorer les signaux d'interruption.
.TP
.I "\-\-version"
Afficher un numéro de version sur la sortie standard et se terminer normalement.

.SH TRADUCTION
Christophe Blaess, 1996-2003.
