.\" Traduction 08/01/1997 par Christophe Blaess (ccb@club-internet.fr)
.\"
.\" MàJ 30/07/2003 coreutils-4.5.3
.TH TRUE 1 "30 juillet 2003" coreutils "Manuel de l utilisateur Linux"
.SH NOM
true \- Réussir à ne rien faire...
.SH SYNOPSIS
.B true
.br
.B true
{\-\-help,\-\-version}
.SH DESCRIPTION
Cette page de manuel documente la version GNU de
.B true
(et probablement toutes les autres versions également).

.B true
ne fait rien d'autre que renvoyer un code de retour valant 0, signifiant
``réussite''. 

Il peut être utilisé pour remplir un shell script lorsqu'une
commande réussie est nécessaire, bien que la commande shell intégrée 
`:' (double-point) fasse la même chose, plus vite.
.SS OPTIONS
Quand la version GNU de
.B true
est invoquée avec un seul argument, les options suivantes sont reconnues :
.TP
.I "\-\-help"
Afficher un message d'aide sur la sortie standard et se terminer normalement.
.TP
.I "\-\-version"
Afficher un numéro de version sur la sortie standard et se terminer normalement.

.SH TRADUCTION
Christophe Blaess, 1997-2003.
