.\" Traduction 09/01/1997 par Christophe Blaess (ccb@club-internet.fr)
.\"
.\" MàJ 30/07/2003 coreutils-4.5.3
.TH TTY 1 "30 juillet 2003" coreutils "Manuel de l utilisateur Linux"
.SH NOM
tty \- Afficher le nom du terminal associe à l'entrée standard.
.SH SYNOPSIS
.B tty
[\-s] [\-\-silent] [\-\-quiet] [\-\-help] [\-\-version]
.SH DESCRIPTION
Cette page de manuel documente la version GNU de
.BR tty .

.B tty
affiche le nom de fichier du tty associé à son entrée standard. Il affiche
`not a tty' si l'entrée standard n'est pas un terminal. 

Son code de
retour vaut :
.nf
0 si l'entrée standard est un tty
1 si l'entrée standard n'est pas un tty
2 si un argument est incorrect
3 s'il y a eu une erreur d'écriture
.fi
.SS OPTIONS
.TP
.I "\-\-help"
Afficher un message d'aide sur la sortie standard et se terminer normalement.
.TP
.I "\-s, \-\-silent, \-\-quiet"
Ne rien afficher, renvoyer simplement le code de retour.
.TP
.I "\-\-version"
Afficher un numéro de version sur la sortie standard et se terminer normalement.

.SH TRADUCTION
Christophe Blaess, 1997-2003.
