.\" Traduction 09/01/1997 par Christophe Blaess (ccb@club-internet.fr)
.\"
.\" MàJ 30/07/2003 coreutils-4.5.3
.TH WHOAMI 1 "30 juillet 2003" coreutils "Manuel de l utilisateur Linux"
.SH NOM
whoami \- Afficher l'U-ID effectif.
.SH SYNOPSIS
.B whoami [\-\-help] [\-\-version]
.SH DESCRIPTION
Cette page de manuel documente la version GNU de
.BR whoami .

.B whoami
affiche le nom d'utilisateur associé à l'U-ID effectif en cours.
C'est équivalent à la commande `id \-un'.
.SS OPTIONS
.TP
.I "\-\-help"
Afficher un message d'aide sur la sortie standard et se terminer normalement.
.TP
.I "\-\-version"
Afficher un numéro de version sur la sortie standard et se terminer normalement.

.SH TRADUCTION
Christophe Blaess, 1997-2003.
