.\" Traduction 09/01/1997 par Christophe Blaess (ccb@club-internet.fr)
.\"
.\" MàJ 30/07/2003 coreutils-4.5.3
.TH YES 1 "30 juillet 2003" coreutils "Manuel de l utilisateur Linux"
.SH NOM
yes \- Afficher indéfiniment une chaîne de caractères, jusqu'à être tué.
.SH SYNOPSIS
.B yes
[string...]
.br
.B yes
{\-\-help,\-\-version}
.SH DESCRIPTION
Cette page de manuel documente la version GNU de
.BR yes .

.B yes
affiche les arguments de sa ligne de commande, séparés par des espaces, et
suivis par un Saut-de-ligne, indéfiniment, jusqu'à ce qu'il soit tué.

Si aucun argument n'est fourni, il répète 'y' suivi d'un Saut-de-ligne,
jusqu'à ce qu'on le tue.
.SS OPTIONS
Quand la version GNU de
.B yes
est invoquée avec un seul argument, les options suivantes sont reconnues :
.TP
.I "\-\-help"
Afficher un message d'aide sur la sortie standard et se terminer normalement.
.TP
.I "\-\-version"
Afficher un numéro de version sur la sortie standard et se terminer normalement.

.SH TRADUCTION
Christophe Blaess, 1997-2003.
